repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: check-ast
  -   id: check-json
  -   id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.4
  hooks:
    # Run the linter. Fix errors, (--extend-select,I) sorts imports.
    - id: ruff
      args: [ --fix, --extend-select, I]
    # Run the formatter.
    - id: ruff-format
