steps:
# 1. Build and Deploy from the subdirectory
- name: 'node:22'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      npm install
      npm run build
      npx firebase-tools deploy --project ${_FIREBASE_PROJECT_ID} --only hosting:${_FIREBASE_SITE_ID} --non-interactive
  dir: 'airsports_static'

substitutions:
  _FIREBASE_PROJECT_ID: 'YOUR_PROJECT_ID'
  _FIREBASE_SITE_ID: 'airsports-info-1747b'

options:
  logging: CLOUD_LOGGING_ONLY
