steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    git submodule update --init
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','--build-arg', 'BUILDKIT_INLINE_CACHE=1','-t','tracker_base','--cache-from','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest','-t','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest','-t','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:${SHORT_SHA}','.']
  env: ['DOCKER_BUILDKIT=1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:${SHORT_SHA}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose','up','-d','tracker_daphne']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export IMAGE_TAG=latest
    docker exec tracker_daphne /bin/bash -c "mkdir -p reports && rm -rf reports/*"
    docker exec tracker_daphne /bin/bash -c "/wait-for-it.sh \"mysql:3306\" -t 30"
    docker exec tracker_daphne /bin/bash -c "pytest"
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose','down']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - '-c'
    - |
      if [$BRANCH_NAME = "main"]
      then
      gcloud builds triggers run standard-deploy  --branch=main --region=europe-west1 --project=${PROJECT_ID}
      fi
images:
- 'europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:${SHORT_SHA}'
- 'europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest'

options:
  logging: CLOUD_LOGGING_ONLY
