steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    git submodule update --init
    mkdir -p secret
    echo '{"type": "service_account", "project_id": "dummy", "private_key_id": "dummy", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCudummy\n-----END PRIVATE KEY-----\n", "client_email": "dummy@dummy.iam.gserviceaccount.com", "client_id": "123", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dummy%40dummy.iam.gserviceaccount.com"}' > secret/airsports-firebase-admin.json
    echo '{}' > secret/application_default_credentials.json
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','--build-arg', 'BUILDKIT_INLINE_CACHE=1','-t','tracker_base','--cache-from','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest','-t','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest','-t','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:${SHORT_SHA}','.']
  env: ['DOCKER_BUILDKIT=1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:${SHORT_SHA}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - '-c'
    - |
      if [ "$BRANCH_NAME" = "main" ]
      then
      gcloud builds triggers run Deploy --branch=main --region=europe-west1 --project=${PROJECT_ID}
      fi
- name: 'gcr.io/cloud-builders/docker'
  id: 'Start Environment'
  args: ['compose','up','-d']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Run Tests'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Waiting for containers to stabilize..."
    sleep 10
    docker ps -a
    
    echo "Preparing reports directory..."
    docker exec -u root tracker_daphne /bin/bash -c "mkdir -p reports && chown django:django reports && rm -rf reports/*" || (docker compose logs tracker_daphne && exit 1)
    
    echo "Waiting for DB..."
    docker exec tracker_daphne /bin/bash -c "/wait-for-it.sh \"mysql:3306\" -t 60" || (docker compose logs && exit 1)
    
    echo "Running pytest..."
    docker exec tracker_daphne /bin/bash -c "pytest --collect-only -p no:cov" || (docker compose logs tracker_daphne && exit 1)
    docker exec tracker_daphne /bin/bash -c "pytest -v -p no:cov --cache-clear" || (docker compose logs tracker_daphne && exit 1)
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose','down']

images:
- 'europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:${SHORT_SHA}'
- 'europe-west3-docker.pkg.dev/${PROJECT_ID}/airsports/tracker_base:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'
timeout: '7200s'
