# Pure local development environment

version: '2'
services:


  tracker_web:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "bash", "-c", "python3 manage.py migrate && cd / && (npm run webpack-local &) && cd /src && python3 manage.py initadmin && python3 manage.py runserver 0.0.0.0:8000" ]
#    command: [ "bash", "-c", "python3 manage.py migrate && cd / && (npm run webpack &) && cd /src && python3 manage.py initadmin && python3 manage.py collectstatic --noinput && bash -c /gunicorn.sh" ]

    container_name: tracker_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
    ports:
      - "8002:8000"
    depends_on:
      - mysql
      - influx

  tracker_processor:
    command: ["/wait-for-it.sh", "mysql:3306", "--",
        "bash", "-c", "python3 position_processor.py" ]
    container_name: tracker_processor
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/
    depends_on:
      - influx
      - mysql

  influx:
    image: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=airsport
      - INFLUXDB_USER=airsport
      - INFLUXDB_USER_PASSWORD=notsecret
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  traccar:
    image: traccar/traccar
    restart: unless-stopped
    container_name: traccar
    volumes:
      - traccar-db:/opt/traccar/data/database
      - ./traccar/configuration/traccar.xml:/opt/traccar/conf/traccar.xml
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
      - 8082:8082
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
#      - MYSQL_DATABASE=traccar
#      - MYSQL_USER=traccar
      - MYSQL_ROOT_PASSWORD=traccar
#      - MYSQL_PASSWORD=traccar
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./traccar/configuration/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

volumes:
  mysqldata:
  traccar-db: