# Pure local development environment

version: '2'
services:


  tracker_web:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "python3 manage.py migrate && cd / && (npm run webpack-local &) && cd /src && python3 manage.py initadmin && python3 manage.py createdefaultscores && redis-cli -h redis -p 6379 FLUSHALL && python3 manage.py runserver 0.0.0.0:8002" ]
#               "bash",  "-c", "sleep 100m" ]

    container_name: tracker_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./weblog:/logs/
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      - influx
      - redis
      - traccar

  tracker_celery:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "celery -A live_tracking_map worker -l DEBUG -f /logs/celery.log" ]
#               "bash",  "-c", "sleep 100m" ]

    container_name: tracker_celery
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./celerylog:/logs/
    depends_on:
      - mysql
      - influx
      - redis


  tracker_processor:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "traccar:8082", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "python3 position_processor.py" ]
    container_name: tracker_processor
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/
      - ./processorlog:/logs/
    depends_on:
      - influx
      - traccar
      - mysql
      - redis

  influx:
    image: influxdb
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=airsport
      - INFLUXDB_USER=airsport
      - INFLUXDB_USER_PASSWORD=notsecret
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  traccar:
    image: traccar/traccar
    restart: unless-stopped
    container_name: traccar
    volumes:
      - traccar-db:/opt/traccar/data/database
      - ./traccar/configuration/traccar.xml:/opt/traccar/conf/traccar.xml
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
      - 8082:8082
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      #      - MYSQL_DATABASE=traccar
      #      - MYSQL_USER=traccar
      - MYSQL_ROOT_PASSWORD=traccar
    #      - MYSQL_PASSWORD=traccar
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./traccar/configuration/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

  redis:
    image: redis
    container_name: redis

volumes:
  influxdb:
  mysqldata:
  traccar-db: