# Pure local development environment

version: '2'
services:
  tracker_web:
    command: ["bash", "-c", "python3 manage.py migrate && cd / && (npm run webpack-local &) && cd /src && python3 manage.py runserver 0.0.0.0:8000"]
    container_name: tracker_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
    ports:
      - "8002:8000"
    depends_on:
      - influx


  tracker_processor:
    command: ["bash", "-c", "python3 position_processor.py"]
    container_name: tracker_processor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/
    depends_on:
      - influx

  influx:
    image: influxdb
    environment:
      - INFLUXDB_DB=airsport
      - INFLUXDB_USER=airsport
      - INFLUXDB_USER_PASSWORD=notsecret
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"