# Pure local development environment

version: '2'
services:
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
      - /tmp/docker/
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - ONLY_SUBDOMAINS=false
      - URL=airsports.no
      - SUBDOMAINS=tracking,traccar,traccarclient,www
      - EMAIL=frankose@ifi.uio.no
      - VALIDATION=http
    volumes:
      - ./swag/config:/config
      - ./assets:/assets/
      - ./src/media:/media
      - ./static:/static
    ports:
      - 443:443
      - 80:80 # Required for certificate validation
    restart: unless-stopped

  tracker_web:
    container_name: tracker_web
    image: airsportsacr.azurecr.io/tracker_web
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
      - MODE=production
    build:
      context: .
      dockerfile: Dockerfile
      target: tracker_web
    volumes:
      - ./secret:/secret
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./weblog:/logs/
      - ./mapserver:/maptiles
    volumes_from:
      - tmp
    ports:
      - "8002:8000"
    depends_on:
      - mysql
      - redis
      - traccar

  tracker_daphne:

    container_name: tracker_daphne
    image: airsportsacr.azurecr.io/tracker_daphne

    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
      target: tracker_daphne
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./daphnelog:/logs/
      - ./mapserver:/maptiles
    volumes_from:
      - tmp
    depends_on:
      - mysql
      - redis



  tracker_celery:

    container_name: tracker_celery
    image: airsportsacr.azurecr.io/tracker_celery

    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
      target: tracker_celery
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./celerylog:/logs/
      - ./mapserver:/maptiles
    volumes_from:
      - tmp
    depends_on:
      - mysql
      - redis



  tracker_processor:
    container_name: tracker_processor
    image: airsportsacr.azurecr.io/tracker_processor

    restart: unless-stopped
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
      target: tracker_processor
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./src:/src/
      - ./processorlog:/logs/
    volumes_from:
      - tmp
    depends_on:
      - traccar
      - mysql
      - redis


  opensky_consumer:
    container_name: opensky_consumer
    image: airsportsacr.azurecr.io/opensky_consumer

    restart: unless-stopped
    environment:
      - OPEN_SKY_USERNAME=${OPEN_SKY_USERNAME}
      - OPEN_SKY_PASSWORD=${OPEN_SKY_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
      target: opensky_consumer
    volumes:
      - ./secret:/secret
      - ./src:/src/
      - ./openskyconsumerlogs:/logs/
    volumes_from:
      - tmp
    depends_on:
      - redis

  ogn_consumer:
    container_name: ogn_consumer
    image: airsportsacr.azurecr.io/ogn_consumer

    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: ogn_consumer
    volumes:
      - ./secret:/secret
      - ./src:/src/
      - ./ognconsumerlogs:/logs/
    volumes_from:
      - tmp
    depends_on:
      - redis


  traccar:
    image: traccar/traccar
    restart: unless-stopped
    container_name: traccar
    volumes:
      - traccar-db:/opt/traccar/data/database
      - ./traccar/configuration/traccar.xml:/opt/traccar/conf/traccar.xml
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
#      - 8082:8082
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      #      - MYSQL_DATABASE=traccar
      #      - MYSQL_USER=traccar
      - MYSQL_ROOT_PASSWORD=traccar
    #      - MYSQL_PASSWORD=traccar
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./traccar/configuration/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    volumes_from:
      - tmp
  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ./celerylog:/logs/celery
      - ./weblog:/logs/web
      - ./processorlog:/logs/processor
    environment:
      LOGS_DIRECTORIES: /logs/*/*.log
      LOGROTATE_COPIES: 60
      LOGROTATE_INTERVAL: daily dateyesterday
      LOGROTATE_DATEFORMAT: -%Y-%m-%d


volumes:
  mysqldata:
  traccar-db: