# Pure local development environment

version: '2'
services:
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
      - /tmp/docker/
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - ONLY_SUBDOMAINS=false
      - URL=airsports.no
      - SUBDOMAINS=tracking,traccar,traccarclient,www
      - EMAIL=frankose@ifi.uio.no
      - VALIDATION=http
    volumes:
      - ./swag/config:/config
      - ./assets:/assets/
      - ./src/media:/media
      - ./static:/static
    ports:
      - 443:443
      - 80:80 # Required for certificate validation
    restart: unless-stopped

  tracker_web:
    #    command: [ "bash", "-c", "python3 manage.py migrate && cd / && (npm run webpack-local &) && cd /src && python3 manage.py initadmin && python3 manage.py createdefaultscores && python3 manage.py runserver 0.0.0.0:8000" ]
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "influx:8086", "--",
                "bash", "-c", "python3 manage.py migrate && cd / && npm run webpack && cd /src && python3 manage.py initadmin && python3 manage.py createdefaultscores && redis-cli -h redis -p 6379 FLUSHALL && python3 manage.py collectstatic --noinput && bash -c /gunicorn.sh" ]

    container_name: tracker_web
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
      - MODE=production
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./weblog:/logs/
      - ./mapserver:/maptiles
    volumes_from:
      - tmp
    ports:
      - "8002:8000"
    depends_on:
      - mysql
      - influx
      - redis
      - traccar

  tracker_daphne:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               #"bash", "-c", "/gunicorn_uvicorn.sh" ]
               "bash", "-c", "/daphne.sh" ]

    container_name: tracker_daphne
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./daphnelog:/logs/
    volumes_from:
      - tmp
    depends_on:
      - mysql
      - influx
      - redis



  tracker_celery:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "celery -A live_tracking_map worker -B -l DEBUG -f /logs/celery.log" ]

    container_name: tracker_celery
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./celerylog:/logs/
    volumes_from:
      - tmp
    depends_on:
      - mysql
      - influx
      - redis


  tracker_beat:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "celery -A live_tracking_map beat -l DEBUG -f /logs/celery.log" ]

    container_name: tracker_beat
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets/
      - ./src:/src/
      - ./reactjs:/reactjs/
      - ./data:/data/
      - ./celerylog:/logs/
    volumes_from:
      - tmp
    depends_on:
      - mysql
      - influx
      - redis


  tracker_processor:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "traccar:8082", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "python3 position_processor.py" ]
    container_name: tracker_processor
    restart: unless-stopped
    environment:
      - AUTHEMAIL_DEFAULT_EMAIL_FROM=${AUTHEMAIL_DEFAULT_EMAIL_FROM}
      - AUTHEMAIL_DEFAULT_EMAIL_BCC=${AUTHEMAIL_DEFAULT_EMAIL_BCC}
      - AUTHEMAIL_EMAIL_HOST=${AUTHEMAIL_EMAIL_HOST}
      - AUTHEMAIL_EMAIL_PORT=${AUTHEMAIL_EMAIL_PORT}
      - AUTHEMAIL_EMAIL_HOST_USER=${AUTHEMAIL_EMAIL_HOST_USER}
      - AUTHEMAIL_EMAIL_HOST_PASSWORD=${AUTHEMAIL_EMAIL_HOST_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./src:/src/
      - ./processorlog:/logs/
    volumes_from:
      - tmp
    depends_on:
      - influx
      - traccar
      - mysql
      - redis


  opensky_consumer:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "traccar:8082", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "python3 opensky_consumer.py $OPEN_SKY_USERNAME $OPEN_SKY_PASSWORD" ]
    container_name: opensky_consumer
    restart: unless-stopped
    environment:
      - OPEN_SKY_USERNAME=${OPEN_SKY_USERNAME}
      - OPEN_SKY_PASSWORD=${OPEN_SKY_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./src:/src/
      - ./openskyconsumerlogs:/logs/
      - ./aircraft_database:/aircraft_database
    volumes_from:
      - tmp
    depends_on:
      - redis

  ogn_consumer:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "traccar:8082", "--",
               "/wait-for-it.sh", "influx:8086", "--",
               "bash", "-c", "python3 ogn_consumer.py" ]
    container_name: ogn_consumer
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./src:/src/
      - ./ognconsumerlogs:/logs/
    volumes_from:
      - tmp
    depends_on:
      - redis

  influx:
    image: influxdb
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=airsport
      - INFLUXDB_USER=airsport
      - INFLUXDB_USER_PASSWORD=notsecret
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  traccar:
    image: traccar/traccar
    restart: unless-stopped
    container_name: traccar
    volumes:
      - traccar-db:/opt/traccar/data/database
      - ./traccar/configuration/traccar.xml:/opt/traccar/conf/traccar.xml
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
#      - 8082:8082
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      #      - MYSQL_DATABASE=traccar
      #      - MYSQL_USER=traccar
      - MYSQL_ROOT_PASSWORD=traccar
    #      - MYSQL_PASSWORD=traccar
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./traccar/configuration/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    volumes_from:
      - tmp
  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ./celerylog:/logs/celery
      - ./weblog:/logs/web
      - ./processorlog:/logs/processor
    environment:
      LOGS_DIRECTORIES: /logs/*/*.log
      LOGROTATE_COPIES: 60
      LOGROTATE_INTERVAL: daily dateyesterday
      LOGROTATE_DATEFORMAT: -%Y-%m-%d


volumes:
  influxdb:
  mysqldata:
  traccar-db: