# Pure local development environment

version: '2'
services:


  tracker_web:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "bash", "-c", "python3 manage.py migrate && cd / && (npm run webpack-local &) && cd /src && python3 manage.py initadmin && python3 manage.py createdefaultscores && redis-cli -h redis -p 6379 FLUSHALL && python3 manage.py runserver 0.0.0.0:8002" ]
#               "bash",  "-c", "sleep 100m" ]

    container_name: tracker_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets
      - ./src:/src
      - ./config:/config
      - ./reactjs:/reactjs
      - ./data:/data
      - ./weblog:/logs
      - ./mapserver:/maptiles
      - ./aircraft_database:/aircraft_database
    environment:
      - MODE=dev
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      - redis
      - traccar

  tracker_celery:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "bash", "-c", "celery -A live_tracking_map worker -E -l DEBUG -f /logs/celery.log" ]
#               "bash",  "-c", "sleep 100m" ]

    container_name: tracker_celery
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./static:/static
      - ./assets:/assets
      - ./src:/src
      - ./reactjs:/reactjs
      - ./data:/data
      - ./celerylog:/logs
    environment:
      - MODE=dev
    depends_on:
      - mysql
      - redis
    ports:
      - "5555:5555"


  tracker_processor:
    command: [ "/wait-for-it.sh", "mysql:3306", "--",
               "/wait-for-it.sh", "traccar:8082", "--",
               "bash", "-c", "python3 position_processor.py" ]
    container_name: tracker_processor
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret:/secret
      - ./django-rest-authemail:/django-rest-authemail
      - ./src:/src
      - ./processorlog:/logs
    depends_on:
      - traccar
      - mysql
      - redis

  traccar:
    image: traccar/traccar
    restart: unless-stopped
    container_name: traccar
    volumes:
      - traccar-db:/opt/traccar/data/database
      - ./traccar/configuration/traccar.xml:/opt/traccar/conf/traccar.xml
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
      - 8082:8082
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      #      - MYSQL_DATABASE=traccar
      #      - MYSQL_USER=traccar
      - MYSQL_ROOT_PASSWORD=traccar
    #      - MYSQL_PASSWORD=traccar
    volumes:
      - mysqldata:/var/lib/mysql
      - ./traccar/configuration/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

  redis:
    image: redis
    container_name: redis

  mapserver:
    image: geodata/mapserver
    volumes:
      - ./mapserver:/maps
    ports:
      - "8080:80"

volumes:
  mysqldata:
  traccar-db: