apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini
  labels:
    app: wordpress
data:
  php-custom.ini: |
    max_file_uploads = 512M
    post_max_size = 512M
    max_execution_time = 300
    max_input_time = 300