apiVersion: batch/v1
kind: Job
metadata:
  name: calculator-job
spec:
  ttlSecondsAfterFinished: 259200  # Three days
  template:
    metadata:
      labels: {}
    spec:
      backoffLimit: 4
      containers:
      - image: europe-west3-docker.pkg.dev/airsports-613ce/airsports/tracker_processor:latest
        resources:
          requests:
            cpu: 500m
            memory: 600Mi # Looks to be around 250 MB
          limit:
            cpu: 400m
        name: calculator-job
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
      restartPolicy: Never  # OnFailure
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets
