apiVersion: batch/v1
kind: Job
metadata:
  name: calculator-job
  namespace: airsports
spec:
  ttlSecondsAfterFinished: 259200  # Three days
  template:
    metadata:
      labels: {}
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      backoffLimit: 4
      containers:
      - image: airsportsacr.azurecr.io/tracker_processor:latest
        resources:
          requests:
            cpu: 50m
            memory: 200Mi # Looks to be around 250 MB
          limit:
            cpu: 400m
        name: calculator-job
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
      restartPolicy: Never  # OnFailure
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets
