export const GET_CONTEST = "GET_CONTEST";
export const GET_CONTEST_SUCCESSFUL = "GET_CONTEST_SUCCESSFUL";
export const GET_CONTEST_FAILED = "GET_CONTEST_FAILED";
export const GET_CONTESTANT_DATA = "GET_CONTESTANT_DATA";
export const GET_CONTESTANT_DATA_FAILED = "GET_CONTESTANT_DATA_FAILED";
export const GET_CONTESTANT_DATA_SUCCESSFUL = "GET_CONTESTANT_DATA_SUCCESSFUL";
export const ADD_CONTESTANT = "ADD_CONTESTANT";
export const SET_DISPLAY = "SET_DISPLAY";

export const DISPLAY_ALL_TRACKS = "DISPLAY_ALL_TRACKS";
export const HIDE_ALL_TRACKS = "HIDE_ALL_TRACKS";
export const DISPLAY_TRACK_FOR_CONTESTANT = "DISPLAY_TRACK_FOR_CONTESTANT";
export const EXCLUSIVE_DISPLAY_TRACK_FOR_CONTESTANT = "EXCLUSIVE_DISPLAY_TRACK_FOR_CONTESTANT";