export const TURNING_POINT_DISPLAY = "TURNING_POINT_DISPLAY";
export const SIMPLE_RANK_DISPLAY = "SIMPLE_RANK_DISPLAY";
export const CONTESTANT_DETAILS_DISPLAY = "CONTESTANT_DETAILS_DISPLAY";

export const ABSOLUTE_SCORE = "ABSOLUTE_SCORE";
export const RELATIVE_SCORE_PERCENTAGE = "RELATIVE_SCORE_PERCENTAGE";