export const GET_CONTEST_LIST = "GET_CONTEST_LIST";
export const GET_CONTEST_LIST_SUCCESSFUL = "GET_CONTEST_LIST_SUCCESSFUL";
export const GET_CONTEST_LIST_FAILED = "GET_CONTEST_LIST_FAILED";

export const GET_CONTEST_RESULTS = "GET_CONTEST_RESULTS";
export const GET_CONTEST_RESULTS_SUCCESSFUL = "GET_CONTEST_RESULTS_SUCCESSFUL";
export const GET_CONTEST_RESULTS_FAILED = "GET_CONTEST_RESULTS_FAILED";

export const GET_CONTEST_TEAMS_LIST = "GET_CONTEST_TEAMS_LIST";
export const GET_CONTEST_TEAMS_LIST_SUCCESSFUL = "GET_CONTEST_TEAMS_LIST_SUCCESSFUL";
export const GET_CONTEST_TEAMS_LIST_FAILED = "GET_CONTEST_TEAMS_LIST_FAILED";