apiVersion: v1
kind: ServiceAccount
metadata:
  name: calculator-scheduler
  annotations:
    # Requires workload identity: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
    # Last command was adding workload pool to cluster: gcloud container clusters update airsports-cluster \
    # --region=europe-north1 \
    # --workload-pool=airsports-613ce.svc.id.goog
    iam.gke.io/gcp-service-account: airsports@airsports-613ce.iam.gserviceaccount.com

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: x20-jobs-sp-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: x20-jobs-sp-rolebinding
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: calculator-scheduler
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: x20-jobs-sp-role
  apiGroup: rbac.authorization.k8s.io