apiVersion: v1
kind: ConfigMap
metadata:
  name: envs-production-other
data:
  REDIS_HOST: {{ include "live_tracking.redisHost" . }}
  REDIS_PORT: "6379"
  MYSQL_HOST: {{ include "live_tracking.mysqlHost" . }}
  MYSQL_PORT: "3306"
  MYSQL_USER: tracker
  MYSQL_DB_NAME: tracker

  TRACCAR_HOST: {{ include "live_tracking.traccarHost" . }}
  TRACCAR_PORT: "8082"
  TRACCAR_PROTOCOL: http

  AUTHEMAIL_EMAIL_HOST: smtp.sendgrid.net
  AUTHEMAIL_EMAIL_PORT: "587"
  AUTHEMAIL_EMAIL_HOST_USER: apikey
  AUTHEMAIL_DEFAULT_EMAIL_FROM: support@airsports.no
  AUTHEMAIL_DEFAULT_EMAIL_BCC: support@airsports.no

  AZURE_ACCOUNT_NAME: {{ .Values.storageAccountName }}
  MEDIA_LOCATION: {{ .Values.mediaLocation }}

  K8S_API: {{ .Values.k8sApi }}

  TRACCAR_USERNAME: {{ .Values.traccarUsername }}
  OPEN_SKY_USERNAME: {{ .Values.openskyUsername }}
  MBTILES_SERVER_URL: {{ .Values.mbtilesUrl }}

