apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tracker-processor
  name: tracker-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tracker-processor
  template:
    metadata:
      labels:
        service: tracker-processor
        date: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 25
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                      - "true"
      # Required for permissions to create kubernetes jobs.
      serviceAccountName: calculator-scheduler
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - image: europe-west3-docker.pkg.dev/airsports-613ce/airsports/tracker_base:{{ .Values.image.tag }}
        command: [ "bash", "-c", "python3 position_processor.py" ]
        resources:
          requests:
            cpu: 500m
            memory: 0.6Gi  # Uses 231 Mi
          limits:
            cpu: 500m
            memory: 0.6Gi
        name: tracker-processor
#        env:
#          - name: K8S_TOKEN
#            valueFrom:
#              secretKeyRef:
#                name: {{ .Values.serviceAccountSecretName }}
#                key: token
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        # Disable cloud logging, permission problem
        # env:
        #   - name: LOG_HANDLER
        #     value: ""
        livenessProbe:
          exec:
            # bash is needed to replace the environment variable
            command: [
              "bash",
              "-c",
              "python -m probes.is_alive || (for pid in $(ps axo pid --no-headers); do ps -p $pid -o command --no-headers ; ps -T -p $pid; done; false )"
            ]
          initialDelaySeconds: 30  # startup takes some time
          periodSeconds: 120
          timeoutSeconds: 10
        readinessProbe:
          exec:
            # bash is needed to replace the environment variable
            command: [
              "python", "-m", "probes.is_ready"
            ]
          initialDelaySeconds: 30  # startup takes some time
          periodSeconds: 120
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
#          - mountPath: /aks_certificate
#            readOnly: true
#            name: aks-certificate
      restartPolicy: Always
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets
#        - name: aks-certificate
#          secret:
#            secretName: {{ .Values.serviceAccountSecretName }}
