apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tracker-celery
  name: tracker-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tracker-celery
  template:
    metadata:
      labels:
        service: tracker-celery
        date: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 25
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                      - "true"
      # Required for permissions to create kubernetes jobs.
      serviceAccountName: calculator-scheduler
      containers:
      - image: europe-west3-docker.pkg.dev/airsports-613ce/airsports/tracker_base:{{ .Values.image.tag }}
        command: [ "bash", "-c", "celery -A live_tracking_map worker -l DEBUG -f /logs/celery.log --concurrency 1" ]
        name: tracker-celery
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        resources:
          requests:
            cpu: 1000m
            memory: 3Gi
          limits:
            cpu: 1000m
            memory: 3Gi
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
        livenessProbe:
          exec:
            # bash is needed to replace the environment variable
            command: [
                "bash",
                "-c",
                "python /src/celery_liveness.py"
            ]
          initialDelaySeconds: 30  # startup takes some time
          periodSeconds: 12  # default is quite often and celery uses a lot cpu/ram then.
          timeoutSeconds: 10
          failureThreshold: 2
        readinessProbe:
          exec:
            # bash is needed to replace the environment variable
            command: [
              "bash",
              "-c",
              "python /src/celery_readiness.py"
            ]
          initialDelaySeconds: 30  # startup takes some time
          periodSeconds: 300  # default is quite often and celery uses a lot cpu/ram then.
          timeoutSeconds: 10
          failureThreshold: 3
      restartPolicy: Always
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets
