apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tracker-web
  name: tracker-web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tracker-web
  template:
    metadata:
      labels:
        service: tracker-web
        date: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 25
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - tracker-web
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                      - "true"
      containers:
      - image: europe-west3-docker.pkg.dev/airsports-613ce/airsports/tracker_base:{{ .Values.image.tag }}
        command: [ "bash", "-c", "/gunicorn.sh" ]
        name: tracker-web
        ports:
          - name: web
            containerPort: 8002
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        resources:
          requests:
            cpu: 1000m
            memory: 3Gi  # Uses 160Mi
          limits:
            cpu: 2000m
            memory: 3Gi
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
        livenessProbe:
          httpGet:
            path: /display/healthz/
            port: web
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /display/readyz/
            port: web
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 2
      restartPolicy: Always
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets

  