apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tracker-daphne
  name: tracker-daphne
spec:
  replicas: 2
  selector:
    matchLabels:
      service: tracker-daphne
  template:
    metadata:
      labels:
        service: tracker-daphne
        date: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 25
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                      - "true"
      initContainers:
        - name: wait-for-db
          image: "alpine:3.6"
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ include "live_tracking.mysqlHost" . }} 3306 && echo mysql ok;
                do sleep 2;
              done
        - name: wait-for-redis
          image: "alpine:3.6"
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ include "live_tracking.redisHost" . }} 6379 && echo redis ok;
                do sleep 2;
              done
      containers:
      - image: europe-west3-docker.pkg.dev/airsports-613ce/airsports/tracker_daphne:{{ .Values.image.tag }}
        #        command: ["/bin/bash", "-c",  "sleep 1h"]
        name: tracker-daphne
        ports:
          - name: daphne
            containerPort: 8003
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        resources:
          requests:
            cpu: 500m
            memory: 500Mi  # Uses 160Mi
          limits:
            cpu: 1000m
            memory: 3Gi
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
        livenessProbe:
          httpGet:
            path: /display/healthz/
            port: daphne
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /display/readyz/
            port: daphne
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
      restartPolicy: Always
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets
        - name: maps-azurefile
          persistentVolumeClaim:
            claimName: maps-azurefile

