apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tracker-celery
  name: tracker-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tracker-celery
  template:
    metadata:
      labels:
        service: tracker-celery
        date: "{{ now | unixEpoch }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: "alpine:3.6"
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ include "live_tracking.mysqlHost" . }} 3306 && echo mysql ok;
                do sleep 2;
              done
        - name: wait-for-redis
          image: "alpine:3.6"
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ include "live_tracking.redisHost" . }} 6379 && echo redis ok;
                do sleep 2;
              done
      containers:
      - image: airsportsacr.azurecr.io/tracker_celery:{{ .Values.image.tag }}
#        command: ["/bin/bash", "-c",  "sleep 1h"]
        name: tracker-celery
        envFrom:
          - configMapRef:
              name: envs-production-other
          - secretRef:
              name: pw-secrets
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
#          limits:
#            cpu: 1000m
#            memory: 1024Mi
        volumeMounts:
          - mountPath: /secret
            readOnly: true
            name: firebase
          - mountPath: /maptiles
            readOnly: true
            name: maps-azurefile
        livenessProbe:
          exec:
            # bash is needed to replace the environment variable
            command: [
                "bash",
                "-c",
                "celery -A live_tracking_map inspect ping -d celery@$HOSTNAME"
            ]
          initialDelaySeconds: 30  # startup takes some time
          periodSeconds: 120  # default is quite often and celery uses a lot cpu/ram then.
          timeoutSeconds: 10
          failureThreshold: 2
      restartPolicy: Always
      volumes:
        - name: firebase
          secret:
            secretName: firebase-secrets
        - name: maps-azurefile
          persistentVolumeClaim:
            claimName: maps-azurefile
