apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tracker-daphne
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tracker-daphne
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
