apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tracker-daphne
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tracker-daphne
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 600 # Very slow scale down (10 mins) to protect long-lived tracking sessions
    