kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: root-external
spec:
  parentRefs:
  - kind: Gateway
    name: external-http
  hostnames:
  - "airsports.no"
  - "www.airsports.no"
  rules:
  - backendRefs:
    - name: tracker-web-service
      port: 80
  - matches:
    - path:
      value: /ws
    backendRefs:
    - name: tracker-daphne-service
      port: 80
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: web-health-check-policy
  namespace: default
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /display/healthz/
  targetRef:
    group: ""
    kind: Service
    name: web-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: daphne-health-check-policy
  namespace: default
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /display/healthz/
  targetRef:
    group: ""
    kind: Service
    name: daphne-service
---
# Replaces BackendConfig
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: daphne-backend-policy
  namespace: default
spec:
  default:
    timeoutSec: 3600
    connectionDraining:
      drainingTimeoutSec: 3600
  targetRef:
    group: ""
    kind: Service
    name: daphne-service