# Used by ingress. Gateway uses certificate manager
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
    name: airsports-no-cert
spec:
  domains:
    - airsports.no
    - www.airsports.no
    - app.airsports.no
    - traccar.airsports.no
    - traccarclient.airsports.no
    - mbtiles.airsports.no