apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-gcloud-cert
spec:
  domains:
    - home.airsports.no
    - gcloud.airsports.no
    - traccar.gcloud.airsports.no
    - traccarclient.gcloud.airsports.no
    - mbtiles.airsports.no