apiVersion: v1
kind: Service
metadata:
  name: tracker-web-service-ingress
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 80
    targetPort: 8002
    protocol: TCP
  selector:
    service: tracker-web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tracker-daphne-service-ingress
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "websocket-backend"}'
spec:
  ports:
  - port: 80
    targetPort: 8003
    protocol: TCP
  selector:
    service: tracker-daphne
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: traccar-service-ingress
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "traccar-client-config"}'
spec:
  ports:
  - port: 8082
    name: http
    targetPort: http
    protocol: TCP
  - port: 5055
    name: osmand
    targetPort: osmand
    protocol: TCP
  selector:
    service: traccar
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: wp-v2-ingress
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "wordpress-backend-config"}'
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/component: wordpress
    app.kubernetes.io/instance: airsportsrelease
    app.kubernetes.io/name: wordpress
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mbtiles-service-ingress
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "mbtiles-backend-config"}'
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    service: mbtiles
  type: ClusterIP
