# Resource to expose the GCS bucket to the Gateway API
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: static-storage-policy
  namespace: default
spec:
  default:
    # Forces CDN to cache everything in this bucket
    cachePolicy:
      cacheMode: CACHE_ALL_STATIC
  targetRef:
    group: ""
    kind: Service
    name: static-storage-service
---
# Service that acts as a bridge to the GCS Bucket
apiVersion: v1
kind: Service
metadata:
  name: static-storage-service
  namespace: default
  annotations:
    # This annotation tells GKE this service is actually a GCS bucket
    networking.gke.io/storage-bucket: airsports-static
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
