from django.urls import path

from display.views import (
    fly_master_data_post,
    generate_hangar_flyer_pdf,
    quick_register,
    renew_token,
    ContestCreateView,
    PersonUpdateView,
    PersonList,
    manifest,
    tracking_qr_code_view,
    get_contestant_map,
    MapGenerationStatusView,
    check_map_generation_status,
    old_tracking_map_redirect,
    get_contestant_default_map,
    get_contestant_email_flight_orders_link,
    EditableRouteDeleteView,
    healthz,
    readyz,
    copy_editable_route,
    download_gpx_track_contestant,
    get_contestant_processing_statistics,
    get_contest_creators_emails,
    navigation_task_view_detailed_score,
    navigation_task_restore_original_scorecard_view,
    navigation_task_scorecard_override_view,
    navigation_task_gatescore_override_view,
    update_flight_order_configurations,
    UserUploadedMapCreate,
    UserUploadedMapList,
    UserUploadedMapUpdate,
    UserUploadedMapDelete,
    download_navigation_task_orders,
    generatenavigation_task_orders_template,
    delete_user_useruploadedmap_permissions,
    change_user_useruploadedmap_permissions,
    add_user_useruploadedmap_permissions,
    list_useruploadedmap_permissions,
    WelcomeEmailExample,
    ContestCreationEmailExample,
    list_editableroute_permissions,
    add_user_editableroute_permissions,
    change_user_editableroute_permissions,
    delete_user_editableroute_permissions,
    import_route,
    delete_user_and_person,
    upgrade_to_organizer,
    user_start_request_profile_deletion,
    user_request_profile_deletion,
)

urlpatterns = [
    path("flymaster/", fly_master_data_post, name="flymaster_post"),
    path("healthz/", healthz),
    path("readyz/", readyz),
    path("useruploadedmaps/", UserUploadedMapList.as_view(), name="useruploadedmap_list"),
    path("useruploadedmaps/create/", UserUploadedMapCreate.as_view(), name="useruploadedmap_add"),
    path("useruploadedmaps/<int:pk>/update/", UserUploadedMapUpdate.as_view(), name="useruploadedmap_change"),
    path("useruploadedmaps/<int:pk>/delete/", UserUploadedMapDelete.as_view(), name="useruploadedmap_delete"),
    path(
        "useruploadedmaps/<int:pk>/permissions/",
        list_useruploadedmap_permissions,
        name="useruploadedmap_permissions_list",
    ),
    path(
        "useruploadedmaps/<int:pk>/permissions/add/",
        add_user_useruploadedmap_permissions,
        name="useruploadedmap_permissions_add",
    ),
    path(
        "useruploadedmaps/<int:pk>/permissions/<int:user_pk>/change/",
        change_user_useruploadedmap_permissions,
        name="useruploadedmap_permissions_change",
    ),
    path(
        "useruploadedmaps/<int:pk>/permissions/<int:user_pk>/delete",
        delete_user_useruploadedmap_permissions,
        name="useruploadedmap_permissions_delete",
    ),
    path("token/renew", renew_token, name="renewtoken"),
    path("users/delete/", delete_user_and_person, name="user_delete"),
    path("users/emails/", get_contest_creators_emails, name="user_emails"),
    path("users/welcomeexample/", WelcomeEmailExample.as_view(), name="welcome_example"),
    path("users/contestexample/", ContestCreationEmailExample.as_view(), name="contestcreation_example"),
    path("contest/create/", ContestCreateView.as_view(), name="contest_create"),
    path(
        "navigationtask/<int:pk>/restorescorecard/",
        navigation_task_restore_original_scorecard_view,
        name="navigationtask_restorescorecard",
    ),
    path(
        "navigationtask/<int:pk>/scoredetails/", navigation_task_view_detailed_score, name="navigationtask_scoredetails"
    ),
    path(
        "navigationtask/<int:pk>/flightorderconfiguration/",
        update_flight_order_configurations,
        name="navigationtask_flightorderconfiguration",
    ),
    path(
        "navigationtask/<int:pk>/updatescorecardoverride/",
        navigation_task_scorecard_override_view,
        name="navigationtask_updatescorecardoverride",
    ),
    path(
        "navigationtask/<int:pk>/updategatescoreoverride/<str:gate_type>/",
        navigation_task_gatescore_override_view,
        name="navigationtask_updategatescoreoverride",
    ),
    path("navigationtask/<int:pk>/qr/", tracking_qr_code_view, name="navigationtask_qr"),
    path(
        "navigationtask/<int:task_id>/mapstatus/<int:contestant_id>/",
        MapGenerationStatusView.as_view(),
        name="map_generation_status",
    ),
    path(
        "navigationtask/<int:task_id>/checkmapstatus/<int:contestant_id>/",
        check_map_generation_status,
        name="check_map_generation_status",
    ),
    path("task/<int:pk>/map/", old_tracking_map_redirect, name="old_tracking_map_redirect"),
    path(
        "navigationtask/<int:pk>/flightordersprogress/",
        generatenavigation_task_orders_template,
        name="navigationtask_flightordersprogress",
    ),
    path(
        "navigationtask/<int:pk>/downloadflightorders/",
        download_navigation_task_orders,
        name="navigationtask_downloadflightorders",
    ),
    path("maplink/<uuid:key>/", get_contestant_email_flight_orders_link, name="email_map_link"),
    path(
        "contestant/<int:pk>/processingstatistics/", get_contestant_processing_statistics, name="processingstatistics"
    ),
    path("contestant/<int:pk>/map/", get_contestant_map, name="contestant_map"),
    path("contestant/<int:pk>/defaultmap/", get_contestant_default_map, name="contestant_default_map"),
    path("contestant/<int:pk>/downloadgpxtrack/", download_gpx_track_contestant, name="contestant_downloadgpxtrack"),
    # path('contestant/<int:pk>/downloadgpxtrack/', download_gpx_track_for_contesant, name="contestant_downloadgpxtrack"),
    path("person/<int:pk>/update/", PersonUpdateView.as_view(), name="person_update"),
    path("person/request_deletion/", user_start_request_profile_deletion, name="user_start_request_profile_deletion"),
    path("person/request_deletion_confirm/", user_request_profile_deletion, name="user_request_profile_deletion"),
    path("person/", PersonList.as_view(), name="person_list"),
    path("manifest/", manifest, name="tracking_manifest"),
    path("users/upgrade/", upgrade_to_organizer, name="upgrade_to_organizer"),
    path("editableroute/import/", import_route, name="editableroute_import"),
    path("editableroute/<int:pk>/delete/", EditableRouteDeleteView.as_view(), name="editableroute_delete"),
    path("editableroute/<int:pk>/copy/", copy_editable_route, name="editableroute_copy"),
    path("editableroute/<int:pk>/permissions/", list_editableroute_permissions, name="editableroute_permissions_list"),
    path(
        "editableroute/<int:pk>/permissions/add/",
        add_user_editableroute_permissions,
        name="editableroute_permissions_add",
    ),
    path(
        "editableroute/<int:pk>/permissions/<int:user_pk>/change/",
        change_user_editableroute_permissions,
        name="editableroute_permissions_change",
    ),
    path(
        "editableroute/<int:pk>/permissions/<int:user_pk>/delete",
        delete_user_editableroute_permissions,
        name="editableroute_permissions_delete",
    ),
    path("navigationtask/<int:pk>/quick_register/", quick_register, name="quick_register"),
    path("navigationtask/<int:pk>/hangar_flyer/", generate_hangar_flyer_pdf, name="hangar_flyer"),
]
