PLAYING_CARDS = [
    # Hearts
    ("Ah", "Ace of hearts"),
    ("Kh", "King of hearts"),
    ("Qh", "Queen of hearts"),
    ("Jh", "Jack of hearts"),
    ("Th", "10 of hearts"),
    ("9h", "9 of hearts"),
    ("8h", "8 of hearts"),
    ("7h", "7 of hearts"),
    ("6h", "6 of hearts"),
    ("5h", "5 of hearts"),
    ("4h", "4 of hearts"),
    ("3h", "3 of hearts"),
    ("2h", "2 of hearts"),
    # Diamonds
    ("Ad", "Ace of diamonds"),
    ("Kd", "King of diamonds"),
    ("Qd", "Queen of diamonds"),
    ("Jd", "Jack of diamonds"),
    ("Td", "10 of diamonds"),
    ("9d", "9 of diamonds"),
    ("8d", "8 of diamonds"),
    ("7d", "7 of diamonds"),
    ("6d", "6 of diamonds"),
    ("5d", "5 of diamonds"),
    ("4d", "4 of diamonds"),
    ("3d", "3 of diamonds"),
    ("2d", "2 of diamonds"),
    # Clubs
    ("Ac", "Ace of clubs"),
    ("Kc", "King of clubs"),
    ("Qc", "Queen of clubs"),
    ("Jc", "Jack of clubs"),
    ("Tc", "10 of clubs"),
    ("9c", "9 of clubs"),
    ("8c", "8 of clubs"),
    ("7c", "7 of clubs"),
    ("6c", "6 of clubs"),
    ("5c", "5 of clubs"),
    ("4c", "4 of clubs"),
    ("3c", "3 of clubs"),
    ("2c", "2 of clubs"),
    # Spades
    ("As", "Ace of spades"),
    ("Ks", "King of spades"),
    ("Qs", "Queen of spades"),
    ("Js", "Jack of spades"),
    ("Ts", "10 of spades"),
    ("9s", "9 of spades"),
    ("8s", "8 of spades"),
    ("7s", "7 of spades"),
    ("6s", "6 of spades"),
    ("5s", "5 of spades"),
    ("4s", "4 of spades"),
    ("3s", "3 of spades"),
    ("2s", "2 of spades"),
]
