# Generated by Django 3.2.10 on 2022-01-21 10:20

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0056_auto_20220117_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationtask',
            old_name='scorecard',
            new_name="original_scorecard"
        ),
    ]
