# Generated by Django 3.2.10 on 2022-01-21 10:25

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0057_auto_20220121_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatescore',
            name='included_fields',
            field=display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False, help_text='List of field names that should be visible in forms'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='included_fields',
            field=display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False, help_text='List of field names that should be visible in forms'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='original_scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name.', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
