# Generated by Django 3.2.10 on 2022-01-21 10:29

from django.db import migrations, models
import django.db.models.deletion

from display.clone_object import clone_object_only_foreign_keys




class Migration(migrations.Migration):

    dependencies = [
        ('display', '0058_auto_20220121_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationtask',
            name='gate_score_override',
        ),
        migrations.RemoveField(
            model_name='navigationtask',
            name='track_score_override',
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='The actual scorecard used for this task. The scorecard may be modified, since it must be a copy of original_scorecard.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_task_override', to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='original_scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name.', on_delete=django.db.models.deletion.PROTECT, related_name='navigation_task_original', to='display.scorecard'),
        ),
    ]
