services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  tracker_daphne:
    command: 'bash -c "while sleep 1000; do :; done"'
    tty: true
    volumes:
      - ./:/workspace/
