apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: retain-azure-disk  # the name of the custom class
  resources:
    requests:
      storage: 2Gi
status: {}