apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: retain-azure-disk  # the name of the custom class
  resources:
    requests:
      storage: 1Gi
status: {}