apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tracker_processor
  namespace: production
  name: tracker_processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tracker_processor
  template:
    metadata:
      labels:
        service: tracker_processor
    spec:
      containers:
      - image: airsportsacr.azurecr.io/tracker_processor
        name: tracker_processor
        envFrom:
          - configMapRef:
              name: envs-production-django
          - configMapRef:
              name: envs-production-postgres
          - secretRef:
              name: secrets-production-django
          - secretRef:
              name: secrets-production-postgres
        resources: {}
      restartPolicy: Always
