# Generated by Django 3.1.6 on 2021-02-12 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_use_email_as_username.models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django_use_email_as_username.models.BaseUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Used to figure out when a not validated personal and user should be deleted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='simulator_tracking_id',
            field=models.CharField(default='qwerty', editable=False, help_text='An automatically generated tracking ID which is distributed to the simulator integration. Persons or contestants identified by this field should not be displayed on the global map.', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='validated',
            field=models.BooleanField(default=True, help_text='Usually true, but set to false for persons created automatically during app API login. This is used to signify that the user profile must be updated. If this remains false for more than a few days, the person object and corresponding user will be deleted from the system.  This must therefore be set to True when submitting an updated profile from the app.'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f80e7785730>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='person',
            name='app_aircraft_registration',
            field=models.CharField(blank=True, default='', help_text='The display name of person positions on the global tracking map (should be an aircraft registration', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='app_tracking_id',
            field=models.CharField(editable=False, help_text='An automatically generated tracking ID which is distributed to the tracking app', max_length=28),
        ),
    ]
