# Generated by Django 3.1.1 on 2020-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='finished_by_time',
            field=models.DateTimeField(null=True),
        ),
    ]
