# Generated by Django 3.1.4 on 2020-12-08 12:26

import display.my_pickled_object_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_type',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_calculator_type',
            field=models.IntegerField(choices=[(0, 'Precision')], default=0, help_text="Supported contest types. Value map: ((0, 'Precision'),)"),
        ),
        migrations.AddField(
            model_name='contestant',
            name='predefined_gate_times',
            field=display.my_pickled_object_field.MyPickledObjectField(blank=True, default=None, editable=False, help_text='Dictionary of gates and their starting times (with time zone)', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='finish_time',
            field=models.DateTimeField(help_text='The finish time of the contest. Not really important, but nice to have'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(help_text='The start time of the contest. Not really important, but nice to have'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The contest wind direction. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The contest wind speed. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='air_speed',
            field=models.FloatField(default=70, help_text='The planned airspeed for the contestant'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contestant_number',
            field=models.IntegerField(help_text='A unique number for the contestant in this contest'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='finished_by_time',
            field=models.DateTimeField(help_text='The time it is expected that the contest has finished and landed (used among other things for knowing when the tracker is busy). Is also used for the gate time for the landing gate', null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='minutes_to_starting_point',
            field=models.FloatField(default=5, help_text='The number of minutes from the take of time until the starting point'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='takeoff_time',
            field=models.DateTimeField(help_text='The time the take of gate (if it exists) should be crossed. Otherwise it is the time power should be applied'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='traccar_device_name',
            field=models.CharField(help_text='ID of physical tracking device that will be brought into the plane', max_length=100),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='backtracking_bearing_difference',
            field=models.FloatField(default=90),
        ),
    ]
