# Generated by Django 3.1.1 on 2020-09-14 09:57

import display.my_pickled_object_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_contestant_finished_by_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='gates',
            field=display.my_pickled_object_field.MyPickledObjectField(default=dict, editable=False),
        ),
    ]
