# Generated by Django 3.1 on 2021-02-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20210209_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='tracker_device_id',
            field=models.CharField(blank=True, help_text='ID of physical tracking device that will be brought into the plane', max_length=100),
        ),
        migrations.AlterField(
            model_name='contestteam',
            name='tracker_device_id',
            field=models.CharField(blank=True, help_text='ID of physical tracking device that will be brought into the plane', max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fcebf28ee18>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
