# Generated by Django 3.1.4 on 2020-12-19 20:53

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20201218_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestanttrack',
            name='gate_actual_times',
            field=display.my_pickled_object_field.MyPickledObjectField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f6f9e8e00d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
