# Generated by Django 3.1.4 on 2020-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20201208_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_calculator_type',
            field=models.IntegerField(choices=[(0, 'Precision')], default=0, help_text="Supported contest calculator types. Different calculators might require different scorecard types, but currently we only support a single calculator.  Value map: ((0, 'Precision'),)"),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contestant_number',
            field=models.PositiveIntegerField(help_text='A unique number for the contestant in this contest'),
        ),
    ]
