# Generated by Django 3.1.6 on 2021-02-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20210212_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Nice image that is shown on top of the event information on the map.', null=True, upload_to='images/contests/'),
        ),
        migrations.AddField(
            model_name='contest',
            name='logo',
            field=models.ImageField(blank=True, help_text='Quadratic logo that is shown next to the event in the event list', null=True, upload_to='images/contestlogos/'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f22ba03cea0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
