# Generated by Django 3.1.4 on 2020-12-19 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20201219_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 22, 22, 3, 624393), help_text='The finish time of the contest. Used for sorting. All navigation tasks should ideally be within this time interval.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 22, 22, 13, 330111), help_text='The start time of the contest. Used for sorting. All navigation tasks should ideally be within this time interval.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f8cd474e048>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
