# Generated by Django 3.1.1 on 2020-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_track_gates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='start_time',
            new_name='takeoff_time',
        ),
        migrations.RemoveField(
            model_name='track',
            name='gates',
        ),
        migrations.AddField(
            model_name='contestant',
            name='minutes_to_starting_point',
            field=models.FloatField(default=5),
        ),
    ]
