# Generated by Django 3.1.4 on 2020-12-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20201208_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.CharField(max_length=200)),
                ('navigator', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('publish_contest', 'Publish contest'),)},
        ),
        migrations.RemoveField(
            model_name='team',
            name='navigator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pilot',
        ),
        migrations.AddField(
            model_name='contest',
            name='is_public',
            field=models.BooleanField(default=False, help_text='The contest is only viewable by unauthenticated users or users without object permissions if this is True'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='minutes_to_starting_point',
            field=models.FloatField(default=5, help_text='The number of minutes from the take-off time until the starting point'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f58518b79d8>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AddField(
            model_name='team',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.crew'),
        ),
    ]
