# Generated by Django 3.1.1 on 2020-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20200915_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='server_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='server_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
