# Generated by Django 3.1.4 on 2020-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0004_auto_20201209_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroplane',
            name='colour',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='aeroplane',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contestant_number',
            field=models.PositiveIntegerField(help_text='A unique number for the contestant in this navigation task'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='finished_by_time',
            field=models.DateTimeField(
                help_text='The time it is expected that the navigationTest has finished and landed (used among other things for knowing when the tracker is busy). Is also used for the gate time for the landing gate',
                null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(
                help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7fd936371b70>',
                null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
