# Generated by Django 3.1.6 on 2021-02-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20210213_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_website',
            field=models.CharField(blank=True, default='', help_text='URL to contest website', max_length=300),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f852a0700d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
