# Generated by Django 3.1.6 on 2021-02-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210215_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='not_applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='contest',
            name='latitude',
            field=models.FloatField(blank=True, default=0, help_text='Approximate location of contest, used for global map display'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='longitude',
            field=models.FloatField(blank=True, default=0, help_text='Approximate location of contest, used for global map display'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='summary_score_sorting_direction',
            field=models.CharField(blank=True, choices=[('desc', 'Descending'), ('asc', 'Ascending')], default='asc', help_text='Whether the lowest (ascending) or highest (ascending) score is the best result', max_length=50),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f94a6217400>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
