# Generated by Django 3.1.1 on 2020-09-19 07:53

import display.my_pickled_object_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20200915_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='starting_line',
            field=display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='navigator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
