# Generated by Django 3.1.4 on 2020-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0005_auto_20201209_0825'),
    ]

    operations = [
        migrations.RunSQL("drop table if exists display_navigationtest;"),
        migrations.RenameModel("Contest", "NavigationTest"),
        migrations.RenameField(
            'contestant',
            "contest",
            "navigation_test"),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('navigation_test', 'contestant_number')},
        ),
    ]
