# Generated by Django 3.1.4 on 2020-12-20 09:22

import display.models
from django.db import migrations, models
import django.db.models.deletion

def set_null(apps, schema_editor):
    Person = apps.get_model('display', 'Person')
    for person in Person.objects.all():
        person.email = None
        person.phone = None
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20201220_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=display.models.CharNullField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=display.models.CharNullField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(set_null),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f0af89f0378>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=display.models.CharNullField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=display.models.CharNullField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
