# Generated by Django 3.1.4 on 2020-12-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20201209_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationtest',
            options={'permissions': (('publish_navigationtest', 'Publish navigation test'),)},
        ),
        migrations.RemoveField(
            model_name='navigationtest',
            name='contest_calculator_type',
        ),
        migrations.AddField(
            model_name='navigationtest',
            name='calculator_type',
            field=models.IntegerField(choices=[(0, 'Precision')], default=0, help_text="Supported navigation test calculator types. Different calculators might require different scorecard types, but currently we only support a single calculator.  Value map: ((0, 'Precision'),)"),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f41c9994b70>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtest',
            name='finish_time',
            field=models.DateTimeField(help_text='The finish time of the navigation test. Not really important, but nice to have'),
        ),
        migrations.AlterField(
            model_name='navigationtest',
            name='is_public',
            field=models.BooleanField(default=False, help_text='The navigation test is only viewable by unauthenticated users or users without object permissions if this is True'),
        ),
        migrations.AlterField(
            model_name='navigationtest',
            name='start_time',
            field=models.DateTimeField(help_text='The start time of the navigation test. Not really important, but nice to have'),
        ),
        migrations.AlterField(
            model_name='navigationtest',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The navigation test wind direction. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AlterField(
            model_name='navigationtest',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The navigation test wind speed. This is used to calculate gate times if these are not predefined.'),
        ),
    ]
