# Generated by Django 3.1.1 on 2020-09-21 18:28

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20200919_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_log', display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False)),
                ('path', display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False)),
                ('annotations', display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False)),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
        ),
    ]
