# Generated by Django 3.1.4 on 2020-12-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20201220_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7fe7dcbb1378>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='tracking_service',
            field=models.CharField(choices=[('traccar', 'Traccar')], default='traccar', help_text="Supported tracking services: (('traccar', 'Traccar'),)", max_length=30),
        ),
    ]
