# Generated by Django 3.1.1 on 2020-09-22 10:59

import display.my_pickled_object_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_contestanttrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestanttrack',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='contestanttrack',
            name='path',
        ),
        migrations.AddField(
            model_name='contestanttrack',
            name='current_state',
            field=models.CharField(default='Waiting...', max_length=200),
        ),
        migrations.AddField(
            model_name='contestanttrack',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestanttrack',
            name='score_per_gate',
            field=display.my_pickled_object_field.MyPickledObjectField(default=dict, editable=False),
        ),
    ]
