# Generated by Django 3.1.4 on 2020-12-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20201209_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationTest',
            new_name='NavigationTask',
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='navigation_test',
            new_name='navigation_task',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='finished_by_time',
            field=models.DateTimeField(help_text='The time it is expected that the navigation task has finished and landed (used among other things for knowing when the tracker is busy). Is also used for the gate time for the landing gate', null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f123f4efb70>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('navigation_task', 'contestant_number')},
        ),
    ]
