# Generated by Django 3.1.7 on 2021-03-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210301_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='annotation_index',
            field=models.IntegerField(default=0, help_text='Internal housekeeping for annotation transmission'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f67e59bf620>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
