# Generated by Django 3.1.4 on 2020-12-21 23:30

import display.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20201220_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(to='display.Team'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f6022b846a8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=display.models.CharNullField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
