# Generated by Django 3.1.1 on 2020-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20200922_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestanttrack',
            name='current_leg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
