# Generated by Django 3.1.7 on 2021-03-09 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20210304_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='calculator_started',
            field=models.BooleanField(default=False, help_text='Set to true when the calculator has started. After this point it is not permitted to change the contestant'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The navigation test wind direction. This is used to calculate gate times if these are not predefined.', validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The navigation test wind speed. This is used to calculate gate times if these are not predefined.', validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f0f8594f950>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The navigation test wind direction. This is used to calculate gate times if these are not predefined.', validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The navigation test wind speed. This is used to calculate gate times if these are not predefined.', validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='calculator',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('poker', 'Poker run'), ('landing', 'Landing')], default='precision', help_text='Supported calculator types', max_length=20),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='task_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('poker', 'Poker run'), ('landing', 'Landing')], default=list, max_length=36),
        ),
    ]
