# Generated by Django 3.1.4 on 2020-12-25 17:33

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20201221_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(blank=True, to='display.Team'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f967bdfc048>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='BasicScoreOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_gate_types', display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False)),
                ('takeoff_gate_duration', models.FloatField(blank=True, default=None, null=True)),
                ('checkpoint_grace_period', models.FloatField(blank=True, default=None, null=True)),
                ('checkpoint_points_per_second', models.FloatField(blank=True, default=None, null=True)),
                ('checkpoint_maximum_points', models.FloatField(blank=True, default=None, null=True)),
                ('checkpoint_not_found', models.FloatField(blank=True, default=None, null=True)),
                ('missing_procedure_turn', models.FloatField(blank=True, default=None, null=True)),
                ('bad_course_grace_time', models.FloatField(blank=True, default=None, null=True)),
                ('bad_course_penalty', models.FloatField(blank=True, default=None, null=True)),
                ('navigation_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.navigationtask')),
            ],
        ),
    ]
