# Generated by Django 3.1.4 on 2020-12-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20201209_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationtask',
            options={'permissions': (('publish_navigationtask', 'Publish navigation test'),)},
        ),
        migrations.RemoveField(
            model_name='navigationtask',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='navigationtask',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='contestant',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The navigation test wind direction. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The navigation test wind speed. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f439bcb1b70>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
