# Generated by Django 3.1.4 on 2020-12-09 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20201209_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='tracker_start_time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), help_text='When the tracker is handed to the contestant, can have no changes to the track after this.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f3175049b70>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
