# Generated by Django 3.1.4 on 2020-12-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20201225_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicscoreoverride',
            name='scorecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f7497e71f28>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
