# Generated by Django 3.1.1 on 2020-09-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_contestanttrack_current_leg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('missed_gate', models.FloatField(default=100)),
                ('gate_timing_per_second', models.FloatField(default=3)),
                ('gate_perfect_limit_seconds', models.FloatField(default=2)),
                ('maximum_gate_score', models.FloatField(default=100)),
                ('backtracking', models.FloatField(default=200)),
                ('missed_procedure_turn', models.FloatField(default=200)),
                ('below_minimum_altitude', models.FloatField(default=500)),
                ('takeoff_time_limit_seconds', models.FloatField(default=60)),
                ('missed_takeoff_gate', models.FloatField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
