# Generated by Django 3.1.7 on 2021-03-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20210309_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatescoreoverride',
            name='navigation_task',
        ),
        migrations.RemoveField(
            model_name='trackscoreoverride',
            name='navigation_task',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='gate_score_override',
            field=models.ManyToManyField(blank=True, to='display.GateScoreOverride'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='track_score_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.trackscoreoverride'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7ffbcefdee18>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='person',
            name='validated',
            field=models.BooleanField(default=True, help_text='Usually true, but set to false for persons created automatically during app API login. This is used to signify that the user profile must be updatedfocus of. If this remains false for more than a few days, the person object and corresponding user will be deleted from the system.  This must therefore be set to True when submitting an updated profile from the app.'),
        ),
    ]
