# Generated by Django 3.1.1 on 2020-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20200923_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='ground_speed',
            new_name='air_speed',
        ),
        migrations.AddField(
            model_name='contest',
            name='wind_direction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
