# Generated by Django 3.1.7 on 2021-03-21 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20210315_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='tasktest',
            options={'ordering': ('index',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='default_sorting',
        ),
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.IntegerField(default=0, help_text='The index of the task when displayed as columns in a table. Indexes are sorted in ascending order to determine column order'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f075794e378>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The navigation test wind direction. This is used to calculate gate times if these are not predefined.', validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The navigation test wind speed. This is used to calculate gate times if these are not predefined.', validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tasktest',
            name='index',
            field=models.IntegerField(default=0, help_text='The index of the task when displayed as columns in a table. Indexes are sorted in ascending order to determine column order'),
        ),
    ]
