# Generated by Django 3.1.4 on 2020-12-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20201209_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('publish_contest', 'Publish contest'),),
            },
        ),
        migrations.AlterModelOptions(
            name='navigationtask',
            options={'permissions': (('publish_navigationtask', 'Publish navigation task'),)},
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f21d74a7ea0>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='display.contest'),
        ),
    ]
