# Generated by Django 3.1.4 on 2020-12-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20201225_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='teams',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f7dcbf86c80>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.CreateModel(
            name='ContestTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_speed', models.FloatField(default=70, help_text='The planned airspeed for the contestant')),
                ('tracking_service', models.CharField(choices=[('traccar', 'Traccar')], default='traccar', help_text="Supported tracking services: (('traccar', 'Traccar'),)", max_length=30)),
                ('traccar_device_name', models.CharField(help_text='ID of physical tracking device that will be brought into the plane', max_length=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.team')),
            ],
            options={
                'unique_together': {('contest', 'team')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_teams',
            field=models.ManyToManyField(blank=True, through='display.ContestTeam', to='display.Team'),
        ),
    ]
