# Generated by Django 3.1.4 on 2020-12-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20201227_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='traccar_device_name',
            new_name='tracker_device_id',
        ),
        migrations.RenameField(
            model_name='contestteam',
            old_name='traccar_device_name',
            new_name='tracker_device_id',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7fea76e3fc80>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
