# Generated by Django 3.1.4 on 2020-12-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20201209_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('publish_contest', 'Can publish contest'),)},
        ),
        migrations.AlterModelOptions(
            name='navigationtask',
            options={'permissions': (('publish_navigationtask', 'Can publish navigation task'),)},
        ),
        migrations.AddField(
            model_name='team',
            name='nation',
            field=models.CharField(default='Norway', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f9be3b26f28>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
