# Generated by Django 3.1.2 on 2020-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20200923_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestanttrack',
            name='last_gate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contestanttrack',
            name='last_gate_time_offset',
            field=models.FloatField(default=0),
        ),
    ]
