# Generated by Django 3.1.7 on 2021-03-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20210321_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksummary',
            name='autosum_scores',
        ),
        migrations.AddField(
            model_name='task',
            name='autosum_scores',
            field=models.BooleanField(default=True, help_text='If true, the front end will sum all tests into TaskSummary when any test is updated'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fa882776268>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
