# Generated by Django 3.1.2 on 2020-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20201126_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestanttrack',
            name='past_finish_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestanttrack',
            name='past_starting_gate',
            field=models.BooleanField(default=False),
        ),
    ]
