# Generated by Django 3.1.4 on 2021-01-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20201227_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='backtracking_maximum_penalty',
            field=models.FloatField(default=-1, help_text='Negative numbers means the maximum is ignored'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f3fc902ef28>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterUniqueTogether(
            name='contestsummary',
            unique_together={('team', 'contest')},
        ),
        migrations.AlterUniqueTogether(
            name='tasksummary',
            unique_together={('team', 'task')},
        ),
    ]
