# Generated by Django 3.1.4 on 2020-12-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0012_auto_20201210_0640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='Route',
        ),
        migrations.AlterModelOptions(
            name='navigationtask',
            options={'ordering': ('start_time', 'finish_time'),
                     'permissions': (('publish_navigationtask', 'Can publish navigation task'),)},
        ),
        migrations.RenameField(
            model_name='navigationtask',
            old_name='track',
            new_name='route'
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(
                help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7fc317325d08>',
                null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='tracker_start_time',
            field=models.DateTimeField(
                help_text='When the tracker is handed to the contestant, can have no changes to the route (e.g. wind and timing) after this.'),
        ),
    ]
