# Generated by Django 3.1.4 on 2021-01-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_auto_20210101_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatescore',
            name='backtracking_after_gate_grace_period_nm',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='gatescore',
            name='backtracking_after_steep_gate_grace_period_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='use_procedure_turns',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f730383bae8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
