# Generated by Django 3.1.3 on 2020-11-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_auto_20201127_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.IntegerField(choices=[(0, 'Precision'), (1, 'ANR')], default=0),
        ),
    ]
