# Generated by Django 3.1.7 on 2021-03-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_auto_20210321_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='tracking_device',
            field=models.CharField(choices=[('device', 'Hardware GPS tracker'), ('pilot_app', "Pilot's Air Sports Live Tracking app"), ('copilot_app', "Copilot's Air Sports Live Tracking app")], default='pilot_app', help_text='The device used for tracking the team', max_length=30),
        ),
        migrations.AddField(
            model_name='contestteam',
            name='tracking_device',
            field=models.CharField(choices=[('device', 'Hardware GPS tracker'), ('pilot_app', "Pilot's Air Sports Live Tracking app"), ('copilot_app', "Copilot's Air Sports Live Tracking app")], default='pilot_app', help_text='The device used for tracking the team', max_length=30),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='tracker_device_id',
            field=models.CharField(blank=True, help_text='ID of physical tracking device that will be brought into the plane. If using the Air Sports Live Tracking app this should be left blank.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contestteam',
            name='tracker_device_id',
            field=models.CharField(blank=True, help_text='ID of physical tracking device that will be brought into the plane. Leave empty if official Air Sports Live Tracking app is used. Note that only a single tracker is to be used per plane.', max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fb9ffb5e510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
