# Generated by Django 3.1.4 on 2020-12-12 14:53

from django.db import migrations


def create_contestants_tracks(apps, schema_editor):
    Contestant = apps.get_model('display', 'Contestant')
    ContestantTrack = apps.get_model('display', 'ContestantTrack')
    for contestant in Contestant.objects.all():
        ContestantTrack.objects.get_or_create(contestant=contestant)


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0013_auto_20201212_1441'),
    ]

    operations = [
        migrations.RunPython(create_contestants_tracks)
    ]
