# Generated by Django 3.1.3 on 2020-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_contest_contest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraccarCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('protocol', models.CharField(default='http', max_length=10)),
                ('address', models.CharField(default='traccar:8082', max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Traccar credentials',
            },
        ),
    ]
