# Generated by Django 3.1.3 on 2020-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_traccarcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestanttrack',
            name='calculator_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('contest', 'contestant_number')},
        ),
    ]
