# Generated by Django 3.1.7 on 2021-03-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_auto_20210324_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='display_background_map',
            field=models.BooleanField(default=True, help_text='If checked the online tracking map shows the mapping background. Otherwise the map will be blank.'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f42bf4aa2f0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='backtracking_bearing_difference',
            field=models.FloatField(default=90, help_text='The bearing difference from the leg direction to initiate backtracking'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='backtracking_grace_time_seconds',
            field=models.FloatField(default=5, help_text='The number of seconds the contestant is allowed to backtrack before backtracking penalty is applied'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='backtracking_penalty',
            field=models.FloatField(default=200, help_text='The number of points given for backtracking'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='below_minimum_altitude_maximum_penalty',
            field=models.FloatField(default=500, help_text='The maximum penalty that can be accumulated for flying below minimum altitude (not applied automatically)'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='below_minimum_altitude_penalty',
            field=models.FloatField(default=500, help_text='Penalty for flying below the minimum altitude (not applied automatically)'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='corridor_width',
            field=models.FloatField(default=0.3, help_text='The corridor width (NM) for ANR tasks'),
        ),
        migrations.AlterField(
            model_name='traccarcredentials',
            name='server_name',
            field=models.CharField(default='A name', max_length=100),
        ),
        migrations.AlterField(
            model_name='traccarcredentials',
            name='token',
            field=models.CharField(default='REPLACE_ME', max_length=100),
        ),
    ]
