# Generated by Django 3.1.4 on 2021-01-04 16:04

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_auto_20210101_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateScoreOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_gate_types', display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False, help_text='List of gates types (eg. tp, secret, sp) that should be overridden (all lower case)')),
                ('checkpoint_grace_period_before', models.FloatField(blank=True, default=None, help_text='The time before a checkpoint that no penalties are awarded', null=True)),
                ('checkpoint_grace_period_after', models.FloatField(blank=True, default=None, help_text='The time after a checkpoint that no penalties are awarded', null=True)),
                ('checkpoint_penalty_per_second', models.FloatField(blank=True, default=None, help_text='The number of points awarded per second outside of the grace period', null=True)),
                ('checkpoint_maximum_penalty', models.FloatField(blank=True, default=None, help_text='The maximum number of penalty points awarded for checkpoint timing', null=True)),
                ('checkpoint_not_found', models.FloatField(blank=True, default=None, help_text='The penalty for missing a checkpoint', null=True)),
                ('missing_procedure_turn_penalty', models.FloatField(blank=True, default=None, help_text='The penalty for missing a procedure turn', null=True)),
                ('bad_course_penalty', models.FloatField(blank=True, default=None, help_text='A amount of points awarded for crossing the gate in the wrong direction (e.g. for landing or takeoff)', null=True)),
                ('bad_crossing_extended_gate_penalty', models.FloatField(blank=True, default=None, help_text='The penalty awarded when crossing the extended gate in the wrong direction (typically used for start gate)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackScoreOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_course_grace_time', models.FloatField(blank=True, default=None, help_text='The number of seconds a bad course can be tolerated before generating a penalty', null=True)),
                ('bad_course_penalty', models.FloatField(blank=True, default=None, help_text='A amount of points awarded for a bad course', null=True)),
                ('bad_course_maximum_penalty', models.FloatField(blank=True, default=None, help_text='A amount of points awarded for a bad course', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gatescore',
            name='bad_course_crossing_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f8f031c0598>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f8f0322b158>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.DeleteModel(
            name='BasicScoreOverride',
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='navigation_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.navigationtask'),
        ),
        migrations.AddField(
            model_name='gatescoreoverride',
            name='navigation_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.navigationtask'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='gate_score_override',
            field=models.ManyToManyField(to='display.GateScoreOverride'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='track_score_override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.trackscoreoverride'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='gate_score_override',
            field=models.ManyToManyField(to='display.GateScoreOverride'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='track_score_override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.trackscoreoverride'),
        ),
    ]
