# Generated by Django 3.1.4 on 2020-12-15 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_auto_20201214_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={},
        ),
        migrations.AddField(
            model_name='contestant',
            name='tracking_service',
            field=models.IntegerField(choices=[(0, 'Traccar')], default=0, help_text="Supported tracking services: ((0, 'Traccar'),)"),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='finished_by_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=utc), help_text='The time it is expected that the navigation task has finished and landed (used among other things for knowing when the tracker is busy). Is also used for the gate time for the landing gate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7efc453b78c8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
