# Generated by Django 3.1.4 on 2020-12-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_auto_20201202_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_limit', models.FloatField(default=60)),
                ('latest_limit', models.FloatField(default=60)),
                ('graceperiod_before', models.FloatField(default=3)),
                ('graceperiod_after', models.FloatField(default=3)),
                ('maximum_penalty', models.FloatField(default=100)),
                ('penalty_per_second', models.FloatField(default=2)),
                ('missed_penalty', models.FloatField(default=100)),
                ('missed_procedure_turn', models.FloatField(default=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='gate_perfect_limit_seconds',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='gate_timing_per_second',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='maximum_gate_score',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='missed_gate',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='missed_procedure_turn',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='missed_takeoff_gate',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='takeoff_time_limit_seconds',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='finish_point_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finish', to='display.gatescore'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='landing_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='display.gatescore'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='secret_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='display.gatescore'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='starting_point_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting', to='display.gatescore'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='takeoff_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeoff', to='display.gatescore'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='turning_point_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turning_point', to='display.gatescore'),
        ),
    ]
