# Generated by Django 3.1.7 on 2021-04-06 15:44
import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0017_auto_20210329_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('gate', models.CharField(default='', max_length=30)),
                ('message', models.TextField(default='')),
                ('string', models.TextField(default='')),
                ('points', models.FloatField()),
                ('planned', models.DateTimeField(blank=True, null=True)),
                ('actual', models.DateTimeField(blank=True, null=True)),
                ('offset_string', models.CharField(blank=True, max_length=200, null=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='TrackAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('message', models.TextField()),
                ('type',
                 models.CharField(choices=[('anomaly', 'Anomaly'), ('information', 'Information')], max_length=30)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
                ('score_log_entry',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.scorelogentry')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='GateCumulativeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=30)),
                ('points', models.FloatField(default=0)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
            options={
                'unique_together': {('contestant', 'gate')},
            },
        ),
        migrations.CreateModel(
            name='ActualGateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
            options={
                'unique_together': {('contestant', 'gate')},
            },
        ),
        migrations.AddField(
            model_name='playingcard',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant', blank=True,
                                    null=True),
            preserve_default=False,
        ),
    ]
