# Generated by Django 3.1.5 on 2021-01-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0017_auto_20210105_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='competition_class_longform',
            field=models.CharField(blank=True, help_text='The class of the contestant, e.g. beginner, professional, et cetera', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='competition_class_shortform',
            field=models.CharField(blank=True, help_text='The abbreviated class of the contestant, e.g. beginner, professional, et cetera', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f26e338fe18>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f26e33a4598>', null=True, on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
