# Generated by Django 3.1.4 on 2020-12-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0017_auto_20201217_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='heading',
            field=models.CharField(default='Dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f4bd34237b8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
