# Generated by Django 3.1.4 on 2020-12-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0018_auto_20201217_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroplane',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/aircraft/'),
        ),
        migrations.AddField(
            model_name='crew',
            name='navigator_picture',
            field=models.ImageField(null=True, upload_to='images/people/'),
        ),
        migrations.AddField(
            model_name='crew',
            name='pilot_picture',
            field=models.ImageField(null=True, upload_to='images/people/'),
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/teams/'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7ff71f98cae8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
