# Generated by Django 3.1.5 on 2021-01-05 20:54

from django.db import migrations, models
import django.db.models.deletion
def delete_clubs(apps, schema_editor):
    NavigationTask = apps.get_model('display', 'NavigationTask')
    Scorecard = apps.get_model("display", "Scorecard")
    for task in NavigationTask.objects.filter(scorecard__isnull = True):
        task.scorecard = Scorecard.objects.first()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0018_auto_20210105_1647'),
    ]

    operations = [
        migrations.RunPython(delete_clubs),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f1c5ae567b8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: FAI Precision 2020, NLF Precision 2020, FAI Air Rally 2020, FAI ANR 2020, FAI ANR 2017', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
            preserve_default=False,
        ),
    ]
