# Generated by Django 3.1.7 on 2021-04-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0019_auto_20210406_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelogentry',
            name='times_string',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fd96417c8c8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='playingcard',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant'),
        ),
        migrations.AlterField(
            model_name='scorelogentry',
            name='offset_string',
            field=models.CharField(default='', max_length=200),
        ),
    ]
