# Generated by Django 3.1.5 on 2021-01-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0019_auto_20210105_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='use_procedure_turns',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7f4625d6b9d8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f4625d6b510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
