# Generated by Django 3.1.5 on 2021-01-06 08:38

from django.db import migrations, models
import django.db.models.deletion
def run(apps, schema_editor):
    GateScore = apps.get_model('display', 'GateScore')
    GateScore.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0020_auto_20210105_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function Contestant.<lambda> at 0x7fef8bf01ae8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fef8bf53510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='finish_point_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finish', to='display.gatescore'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='landing_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='display.gatescore'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='secret_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret', to='display.gatescore'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='starting_point_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting', to='display.gatescore'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='takeoff_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeoff', to='display.gatescore'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='turning_point_gate_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turning_point', to='display.gatescore'),
        ),
        migrations.RunPython(run)
    ]
