# Generated by Django 3.1.8 on 2021-04-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0021_auto_20210411_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='A featured contest is visible to all (if it is public). If it is not featured, a direct link is required to access it.'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='A featured navigation is visible to all (if public). Otherwise a direct link is required to access it'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f1cb00db620>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
