# Generated by Django 3.1.8 on 2021-04-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0022_auto_20210411_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktest',
            name='navigation_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.navigationtask'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f0c81ce8670>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
