# Generated by Django 3.1.5 on 2021-01-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0023_auto_20210106_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='scorecard',
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f90f28c6510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
