# Generated by Django 3.2.1 on 2021-05-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0023_auto_20210416_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='allow_self_management',
            field=models.BooleanField(default=False, help_text='If checked, authenticated users will be allowed to set up themselves as a contestant after having registered for the contest.'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='summary_score_sorting_direction',
            field=models.CharField(blank=True, choices=[('desc', 'Descending'), ('asc', 'Ascending')], default='asc', help_text='Whether the lowest (ascending) or highest (descending) score is the best result', max_length=50),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fc6a2e1e0d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='task',
            name='autosum_scores',
            field=models.BooleanField(default=True, help_text='If true, the server sum all tests into TaskSummary when any test is updated'),
        ),
    ]
