# Generated by Django 3.2.1 on 2021-05-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0024_auto_20210512_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='waypoint_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fc7519e60d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
