# Generated by Django 3.1.5 on 2021-01-08 15:43

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0024_auto_20210106_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fa124a2bbf8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
