# Generated by Django 3.2.1 on 2021-05-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0025_auto_20210520_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='waypoint_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fd6698110d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
