# Generated by Django 3.1.5 on 2021-01-09 18:52

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0025_auto_20210108_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationtask',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='contest',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Oslo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='gate_score_override',
            field=models.ManyToManyField(blank=True, to='display.GateScoreOverride'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fe60a8f4bf8>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='track_score_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.trackscoreoverride'),
        ),
    ]
