# Generated by Django 3.1.5 on 2021-01-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0026_auto_20210109_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationtask',
            name='calculator_type',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='calculator',
            field=models.IntegerField(choices=[(0, 'Precision')], default=0, help_text='Supported calculator types'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f4b5667d488>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
