# Generated by Django 3.2.1 on 2021-05-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0026_auto_20210520_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='score_sorting_direction',
            field=models.CharField(blank=True, choices=[('desc', 'Descending'), ('asc', 'Ascending')], default='asc', help_text='Whether the lowest (ascending) or highest (descending) score is the best result', max_length=50),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f5d646430d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
