# Generated by Django 3.1.5 on 2021-01-26 08:00

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0027_auto_20210124_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='corridor_grace_time',
            field=models.IntegerField(default=5, help_text='The corridor grace time for ANR tasks'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='corridor_width',
            field=models.FloatField(default=0.3, help_text='The corridor width for ANR tasks'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='task_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR corridor')], default=list, max_length=22),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='corridor_grace_time',
            field=models.FloatField(blank=True, default=None, help_text='The grace time of the ANR corridor', null=True),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='corridor_width',
            field=models.FloatField(blank=True, default=None, help_text='The width of the ANR corridor', null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fb91e23e730>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='calculator',
            field=models.IntegerField(choices=[(0, 'Precision'), (1, 'ANR Corridor')], default=0, help_text='Supported calculator types'),
        ),
    ]
