# Generated by Django 3.1.5 on 2021-01-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0028_auto_20210126_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='corridor_maximum_penalty',
            field=models.FloatField(default=-1, help_text='The maximum penalty for leaving the corridor'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='corridor_outside_penalty',
            field=models.FloatField(default=200, help_text='The penalty awarded for leaving the ANR corridor'),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='corridor_maximum_penalty',
            field=models.FloatField(blank=True, default=None, help_text='The maximum penalty for leaving the corridor', null=True),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='corridor_outside_penalty',
            field=models.FloatField(blank=True, default=None, help_text='The penalty awarded for leaving the ANR corridor', null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f728456a598>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
