# Generated by Django 3.1.5 on 2021-01-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0029_auto_20210126_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatescore',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f1d34926510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='corridor_outside_penalty',
            field=models.FloatField(default=3, help_text='The penalty awarded for leaving the ANR corridor'),
        ),
    ]
