# Generated by Django 3.2.6 on 2021-08-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0029_auto_20210730_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='display_secrets',
            field=models.BooleanField(default=True, help_text='If checked secret gates will be displayed on the map. Otherwise the map will only include gates that are not secret, and also not display annotations related to the secret gates.'),
        ),
        migrations.AddField(
            model_name='trackannotation',
            name='gate',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trackannotation',
            name='gate_type',
            field=models.CharField(blank=True, choices=[('tp', 'Turning point'), ('sp', 'Starting point'), ('fp', 'Finish point'), ('secret', 'Secret point'), ('to', 'Takeoff gate'), ('ldg', 'Landing gate'), ('isp', 'Intermediary starting point'), ('ifp', 'Intermediary finish point')], default='tp', max_length=30),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fefff504ca0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
