# Generated by Django 3.2.6 on 2021-08-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0030_auto_20210803_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestanttrack',
            old_name='past_finish_gate',
            new_name='calculator_started',
        ),
        migrations.RenameField(
            model_name='contestanttrack',
            old_name='past_starting_gate',
            new_name='passed_finish_gate',
        ),
        migrations.AddField(
            model_name='contestanttrack',
            name='passed_starting_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fcfb7ae51f0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
