# Generated by Django 3.1.5 on 2021-01-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0030_auto_20210127_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='adaptive_start',
            field=models.BooleanField(default=False, help_text='If true, takeoff time and minutes to starting point is ignored. Start time is set to the closest minute to the time crossing the starting line. This is typically used for a case where it is difficult to control the start time because of external factors such as ATC.'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f9db324e0d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
