# Generated by Django 3.2.6 on 2021-08-10 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0031_auto_20210806_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fc5bef36700>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.CreateModel(
            name='EmailMapLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
        ),
    ]
