# Generated by Django 3.1.5 on 2021-01-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0031_auto_20210128_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='rounded_corners',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f57641ef510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
