# Generated by Django 3.1.5 on 2021-01-30 10:50

import display.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0032_auto_20210129_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f147e275510>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.CreateModel(
            name='Prohibited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', display.my_pickled_object_field.MyPickledObjectField(default=list, editable=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.route')),
            ],
        ),
    ]
