# Generated by Django 3.2.6 on 2021-08-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0033_auto_20210815_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableroute',
            name='route_type',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('poker', 'Poker run'), ('landing', 'Landing')], default='precision', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f4916ce80d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
