# Generated by Django 3.1.5 on 2021-01-31 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0033_auto_20210130_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibited',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='prohibited_zone_penalty',
            field=models.FloatField(default=200, help_text='Penalty for entering prohibited zone such as controlled airspace or other prohibited areas'),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='prohibited_zone_penalty',
            field=models.FloatField(default=200, help_text='Penalty for entering prohibited zone such as controlled airspace or other prohibited areas'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fd0ce686e18>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
