# Generated by Django 3.1.5 on 2021-01-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0034_auto_20210131_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='below_minimum_altitude_maximum_penalty',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fe7541b9f28>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
