# Generated by Django 3.2.6 on 2021-08-18 21:17

import display.fields.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0035_auto_20210818_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmaplink',
            name='orders',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f63fef2a0d0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
