# Generated by Django 3.1.6 on 2021-02-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0035_auto_20210131_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='minutes_to_landing',
            field=models.FloatField(default=5, help_text='The number of minutes from the finish point to the contestant should have landed'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='minutes_to_starting_point',
            field=models.FloatField(default=5, help_text='The number of minutes from the take-off time until the starting point'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='wind_direction',
            field=models.FloatField(default=0, help_text='The navigation test wind direction. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='wind_speed',
            field=models.FloatField(default=0, help_text='The navigation test wind speed. This is used to calculate gate times if these are not predefined.'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fab80e72b70>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
