# Generated by Django 3.1.6 on 2021-02-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0036_auto_20210203_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ('takeoff_time',)},
        ),
        migrations.AddField(
            model_name='contest',
            name='latitude',
            field=models.FloatField(default=0, help_text='Approximate location of contest, used for global map display'),
        ),
        migrations.AddField(
            model_name='contest',
            name='longitude',
            field=models.FloatField(default=0, help_text='Approximate location of contest, used for global map display'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f5acb6daea0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
