# Generated by Django 3.2.6 on 2021-08-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0036_auto_20210818_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='default_line_width',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='default_map',
            field=models.CharField(choices=[('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f14b982aca0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
