# Generated by Django 3.1.6 on 2021-02-09 07:17

import display.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0037_auto_20210208_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='app_aircraft_registration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='app_tracking_id',
            field=display.models.CharNullField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f36a45d9ea0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
