# Generated by Django 3.2.6 on 2021-08-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0037_auto_20210824_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='penalty_zone_grace_time',
            field=models.FloatField(default=3, help_text='The number of seconds the contestant can be within the penalty zone before getting penalty'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='penalty_zone_maximum',
            field=models.FloatField(default=100, help_text='Maximum penalty within a single zone'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='penalty_zone_penalty_per_second',
            field=models.FloatField(default=3, help_text='The number of points per second beyond the grace time while inside the penalty zone'),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='penalty_zone_grace_time',
            field=models.FloatField(default=3, help_text='The number of seconds the contestant can be within the penalty zone before getting penalty'),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='penalty_zone_maximum',
            field=models.FloatField(default=100, help_text='Maximum penalty within a single zone'),
        ),
        migrations.AddField(
            model_name='trackscoreoverride',
            name='penalty_zone_penalty_per_second',
            field=models.FloatField(default=3, help_text='The number of points per second beyond the grace time while inside the penalty zone'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f35ef507d30>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
