# Generated by Django 3.2.6 on 2021-08-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0038_auto_20210825_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorelogentry',
            options={'ordering': ('time', 'pk')},
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='corridor_width',
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='default_map',
            field=models.CharField(choices=[('/maptiles/33_N250.sid', '33 N250.sid'), ('/maptiles/germany1', 'Germany1'), ('/maptiles/germany_map', 'Germany Map'), ('/maptiles/m517', 'M517'), ('/maptiles/Norway_N250', 'Norway N250'), ('/maptiles/Norway_N250.zip', 'Norway N250.zip'), ('/maptiles/rzdm2020', 'Rzdm2020'), ('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fb0972d5310>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
