# Generated by Django 3.2.6 on 2021-08-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0039_auto_20210829_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='corridor_width',
            field=models.FloatField(blank=True, default=0.5),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7ff289a0e430>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
