# Generated by Django 3.2.7 on 2021-09-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0040_auto_20210829_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmaplink',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='emailmaplink',
            name='orders',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fdb1f035310>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
