# Generated by Django 3.2.7 on 2021-09-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0041_auto_20210916_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fac6eea7700>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
