# Generated by Django 3.2.7 on 2021-09-29 20:20

import display.fields.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0042_auto_20210917_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f815a25c430>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='trackannotation',
            name='type',
            field=models.CharField(choices=[('anomaly', 'Anomaly'), ('information', 'Information'), ('debug', 'Debug')], max_length=30),
        ),
        migrations.CreateModel(
            name='ContestantUploadedTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False, help_text='List of traccar position reports (Dict)')),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
        ),
    ]
