# Generated by Django 3.2.7 on 2021-10-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0043_auto_20210929_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='calculation_delay_minutes',
            field=models.FloatField(default=0, help_text='Number of minutes processions and scores should be delayed before they are made available on the tracking map.'),
        ),
        migrations.AlterField(
            model_name='aeroplane',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contest',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Nice image that is shown on top of the event information on the map.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.ImageField(blank=True, help_text='Quadratic logo that is shown next to the event in the event list', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='default_map',
            field=models.CharField(choices=[('/maptiles/Norway_N250', 'Norway N250'), ('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fc5ab649310>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='validated',
            field=models.BooleanField(default=True, help_text='Usually true, but set to false for persons created automatically during app API login. This is used to signify that the user profile must be updated. If this remains false for more than a few days, the person object and corresponding user will be deleted from the system.  This must therefore be set to True when submitting an updated profile from the app.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
