# Generated by Django 3.2.7 on 2021-10-13 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0044_auto_20211007_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationtask',
            name='calculation_delay_minutes',
            field=models.FloatField(default=0, help_text='Number of minutes processions and scores should be delayed before they are made available on the tracking map.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f2949cf9310>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
