# Generated by Django 3.2.8 on 2021-10-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0045_auto_20211013_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7eff66bebaf0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.CreateModel(
            name='ContestantReceivedPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('course', models.FloatField()),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.contestant')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
