# Generated by Django 3.2.8 on 2021-10-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0046_auto_20211022_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantreceivedposition',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contestant'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f9ee3414af0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
