# Generated by Django 3.2.8 on 2021-11-07 18:19

from django.db import migrations, models
import django.db.models.deletion

from display.fields.my_pickled_object_field import MyPickledObjectField


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0047_auto_20211022_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelogentry',
            name='type',
            field=models.CharField(choices=[('anomaly', 'Anomaly'), ('information', 'Information'), ('debug', 'Debug')], default='information', max_length=30),
        ),
        migrations.AlterField(
            model_name='editableroute',
            name='route_type',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('airsports', 'Airsports'), ('poker', 'Poker run'), ('landing', 'Landing')], default='precision', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f26f9331b80>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='calculator',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('poker', 'Poker run'), ('landing', 'Landing'), ('airsports', 'Airsports')], default='precision', help_text='Supported calculator types', max_length=20),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='task_type',
            field=MyPickledObjectField(default=list),
        ),
    ]
