# Generated by Django 3.2.9 on 2021-11-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0048_auto_20211107_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibited',
            name='tooltip_offset',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7f6f23e37a60>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
