# Generated by Django 3.2.9 on 2021-11-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0050_auto_20211114_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='interpolated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fdf57cfc280>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
