# Generated by Django 3.2.9 on 2021-11-26 11:23

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0052_auto_20211125_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Optional, if omitted country will be inferred from latitude and longitude if they are provided.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fa0a994d160>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
