# Generated by Django 3.2.9 on 2021-12-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0054_auto_20211206_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='tasktest',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name. Currently existing scorecards: <function NavigationTask.<lambda> at 0x7fa9aa3781f0>', on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
    ]
