# Generated by Django 3.2.10 on 2022-01-21 12:59

import display.fields.my_pickled_object_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0056_auto_20220117_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationtask',
            old_name='scorecard',
            new_name="original_scorecard"
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='original_scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard name.',
                                    related_name='navigation_task_original',
                                    on_delete=django.db.models.deletion.PROTECT, to='display.scorecard'),
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='gate_score_override',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='track_score_override',
        ),
        migrations.RemoveField(
            model_name='navigationtask',
            name='gate_score_override',
        ),
        migrations.RemoveField(
            model_name='navigationtask',
            name='track_score_override',
        ),
        migrations.AddField(
            model_name='gatescore',
            name='included_fields',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False,
                                                                              help_text='List of field names that should be visible in forms'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='included_fields',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False,
                                                                              help_text='List of field names that should be visible in forms'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='original',
            field=models.BooleanField(default=True,
                                      help_text='Signifies that this has been created manually and is not a copy'),
        ),
        migrations.AddField(
            model_name='navigationtask',
            name='scorecard',
            field=models.ForeignKey(
                help_text='The actual scorecard used for this task. The scorecard may be modified, since it must be a copy of original_scorecard.',
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_task_override',
                to='display.scorecard'),
        ),
    ]
