# Generated by Django 3.2.10 on 2022-01-21 12:41

from django.db import migrations




class Migration(migrations.Migration):
    dependencies = [
        ('display', '0057_auto_20220121_1259'),
    ]

    operations = [
    ]
