# Generated by Django 3.2.10 on 2022-01-21 13:10

from django.db import migrations

from display.utilities.clone_object import clone_object_only_foreign_keys


def clone_scorecards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    NavigationTask = apps.get_model("display", "NavigationTask")
    for navigation_task in NavigationTask.objects.using(db_alias).all():
        navigation_task.scorecard = clone_object_only_foreign_keys(navigation_task.original_scorecard, {
            "name": f"{navigation_task.pk}_{navigation_task.original_scorecard.name}", "original": False})
        navigation_task.save(update_fields=("scorecard",))


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0058_manual'),
    ]

    operations = [
        migrations.RunPython(clone_scorecards),
    ]
