# Generated by Django 3.2.10 on 2022-01-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0060_auto_20220121_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatescore',
            name='name',
        ),
    ]
