# Generated by Django 3.2.10 on 2022-01-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0061_remove_gatescore_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GateScoreOverride',
        ),
        migrations.DeleteModel(
            name='TrackScoreOverride',
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.OneToOneField(help_text='The actual scorecard used for this task. The scorecard may be modified, since it must be a copy of original_scorecard.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_task_override', to='display.scorecard'),
        ),
    ]
