# Generated by Django 3.2.10 on 2022-01-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0063_auto_20220122_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatescore',
            options={'ordering': ('gate_type',)},
        ),
        migrations.AddField(
            model_name='scorecard',
            name='shortcut_name',
            field=models.CharField(default='shortcut_default', help_text=" Shortcut reference to latest scorecard version, e.g. 'FAI Precision' currently links to 'FAI Precision 2020'. This is the field that is used for lookups through the API, but the name is still used everywhere else", max_length=300),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='original_scorecard',
            field=models.ForeignKey(help_text='Reference to an existing scorecard', on_delete=django.db.models.deletion.PROTECT, related_name='navigation_task_original', to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='scorecard',
            field=models.OneToOneField(help_text='The actual scorecard used for this task. The scorecard may be modified, since it must be a copy of original_scorecard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_task_override', to='display.scorecard'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='name',
            field=models.CharField(default='default', max_length=300, unique=True),
        ),
    ]
