# Generated by Django 3.2.10 on 2022-01-25 08:14

from django.db import migrations


def create_unique_shortcut_names(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Scorecard = apps.get_model("display", "Scorecard")
    count = 0
    for scorecard in Scorecard.objects.using(db_alias).all():
        if not scorecard.original:
            scorecard.shortcut_name = scorecard.name + f"_{count}"
            count += 1
            scorecard.save()


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0065_auto_20220125_0811'),
    ]

    operations = [
        migrations.RunPython(create_unique_shortcut_names)
    ]
