# Generated by Django 3.2.10 on 2022-02-09 21:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0068_alter_scorecard_shortcut_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOrderConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=50)),
                ('include_turning_points', models.BooleanField(default=True)),
                ('map_dpi', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500)])),
                ('map_zoom_level', models.IntegerField(default=12)),
                ('map_orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=30)),
                ('map_scale', models.IntegerField(choices=[(150, '1:150,000'), (200, '1:200,000'), (250, '1:250,000'), (300, '1:300,000'), (0, 'Fit page')], default=0)),
                ('map_source', models.CharField(choices=[('/maptiles/Finland', 'Finland'), ('/maptiles/Switzerland', 'Switzerland'), ('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=50)),
                ('map_include_annotations', models.BooleanField(default=True)),
                ('map_include_waypoints', models.BooleanField(default=True)),
                ('map_line_width', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('map_line_colour', models.CharField(default='#0000ff', max_length=7)),
                ('navigation_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.navigationtask')),
            ],
        ),
    ]
