# Generated by Django 3.2.10 on 2022-02-09 22:04

from django.db import migrations


def create_flight_order_configuration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    NavigationTask = apps.get_model("display", "NavigationTask")
    FlightOrderConfiguration = apps.get_model("display", "FlightOrderConfiguration")
    for navigation_task in NavigationTask.objects.using(db_alias).all():
        FlightOrderConfiguration.objects.get_or_create(navigation_task=navigation_task)


class Migration(migrations.Migration):
    dependencies = [
        ('display', '0069_flightorderconfiguration'),
    ]

    operations = [
        migrations.RunPython(create_flight_order_configuration)
    ]
