# Generated by Django 3.2.10 on 2022-02-10 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0070_auto_20220209_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightorderconfiguration',
            name='map_minute_mark_line_width',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
