# Generated by Django 3.2.12 on 2022-02-10 14:16

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0072_auto_20220210_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/maptiles'), upload_to='user_maps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
