# Generated by Django 3.2.12 on 2022-02-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0073_useruploadedmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightorderconfiguration',
            name='map_user_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.useruploadedmap'),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_source',
            field=models.CharField(choices=[('/maptiles/Finland', 'Finland'), ('/maptiles/Switzerland', 'Switzerland'), ('/maptiles/user_maps', 'User Maps'), ('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=50),
        ),
    ]
