# Generated by Django 3.2.12 on 2022-02-11 12:46

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0074_auto_20220210_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmap',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_source',
            field=models.CharField(blank=True, choices=[('/maptiles/Finland', 'Finland'), ('/maptiles/Switzerland', 'Switzerland'), ('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=50),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_user_source',
            field=models.ForeignKey(blank=True, help_text='Overrides whatever is chosen in map source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.useruploadedmap'),
        ),
        migrations.AlterField(
            model_name='useruploadedmap',
            name='map_file',
            field=models.FileField(help_text='File must be of type MBTILES. This can be generated for instance using MapTile Desktop', storage=django.core.files.storage.FileSystemStorage(location='/maptiles'), upload_to='user_maps', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mbtiles'])]),
        ),
    ]
