# Generated by Django 3.2.12 on 2022-02-11 22:24

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0075_auto_20220211_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableroute',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='route_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='useruploadedmap',
            name='map_file',
            field=models.FileField(help_text='File must be of type MBTILES. This can be generated for instance using MapTile Desktop', storage=django.core.files.storage.FileSystemStorage(location='/maptiles/user_maps'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mbtiles'])]),
        ),
        migrations.AlterField(
            model_name='useruploadedmap',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='map_thumbnails/'),
        ),
    ]
