# Generated by Django 3.2.12 on 2022-02-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0077_auto_20220212_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editableroute',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='calculator_started',
        ),
    ]
