# Generated by Django 3.2.12 on 2022-02-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0079_gatescore_backtracking_before_gate_grace_period_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktest',
            name='navigation_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.navigationtask'),
        ),
    ]
