# Generated by Django 3.2.12 on 2022-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0080_alter_tasktest_navigation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='free_text',
            field=models.TextField(default='', help_text='Free text (with HTML) that is included at the bottom of the scorecard box'),
        ),
    ]
