# Generated by Django 3.2.14 on 2022-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0082_auto_20220706_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraccarCredentials',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='adaptive_start',
            field=models.BooleanField(default=False, help_text='If true, takeoff time and minutes to starting point is ignored. Start time is set to the closest minute to the time crossing the infinite starting line in the correct direction. This is typically used for a case where it is difficult to control the start time because of external factors such as ATC.'),
        ),
        migrations.AlterField(
            model_name='gatescore',
            name='gate_type',
            field=models.CharField(choices=[('tp', 'Turning Point'), ('sp', 'Starting Point'), ('fp', 'Finish Point'), ('secret', 'Secret Point'), ('to', 'Takeoff Gate'), ('ldg', 'Landing Gate'), ('isp', 'Intermediary Starting Point'), ('ifp', 'Intermediary Finish Point'), ('dummy', 'Dummy'), ('ul', 'Unknown leg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trackannotation',
            name='gate_type',
            field=models.CharField(blank=True, choices=[('tp', 'Turning Point'), ('sp', 'Starting Point'), ('fp', 'Finish Point'), ('secret', 'Secret Point'), ('to', 'Takeoff Gate'), ('ldg', 'Landing Gate'), ('isp', 'Intermediary Starting Point'), ('ifp', 'Intermediary Finish Point'), ('dummy', 'Dummy'), ('ul', 'Unknown leg')], default='tp', max_length=30),
        ),
    ]
