# Generated by Django 3.2.16 on 2023-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0083_auto_20221002_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightorderconfiguration',
            name='map_include_meridians_and_parallels_lines',
            field=models.BooleanField(default=True, help_text='If true, navigation map is overlaid with meridians and parallels. Disable if map source already has this'),
        ),
    ]
