# Generated by Django 3.2.16 on 2023-02-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0084_flightorderconfiguration_map_include_meridians_and_parallels_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='shortcut_name',
            field=models.CharField(default='shortcut_default', help_text="Shortcut reference to latest scorecard version, e.g. 'FAI Precision' currently links to 'FAI Precision 2020'. This is the field that is used for lookups through the API, but the name is still used everywhere else", max_length=255, unique=True),
        ),
    ]
