# Generated by Django 3.2.18 on 2023-03-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0086_auto_20230219_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightorderconfiguration',
            old_name='map_include_waypoints',
            new_name='map_plot_track_between_waypoints',
        ),
    ]
