# Generated by Django 3.2.18 on 2023-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0087_rename_map_include_waypoints_flightorderconfiguration_map_plot_track_between_waypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightorderconfiguration',
            name='include_turning_points',
        ),
        migrations.AddField(
            model_name='flightorderconfiguration',
            name='include_turning_point_images',
            field=models.BooleanField(default=True, help_text='Includes one or more pages with aerial photos of each turning point (turns in a anr corridor is not considered a turning point).'),
        ),
    ]
