# Generated by Django 3.2.10 on 2022-02-09 22:04

from django.db import migrations


def reset_task_type(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Scorecard = apps.get_model("display", "Scorecard")
    for scorecard in Scorecard.objects.using(db_alias).all():
        if hasattr(scorecard, "navigation_task_override") and scorecard.navigation_task_override.original_scorecard:
            scorecard.task_type = scorecard.navigation_task_override.original_scorecard.task_type
            scorecard.save()


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0090_alter_scorecard_task_type"),
    ]

    operations = [migrations.RunPython(reset_task_type)]
