# Generated by Django 4.1.7 on 2023-06-11 11:30

import display.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0092_alter_contest_summary_score_sorting_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmap',
            name='unprotected',
            field=models.BooleanField(default=False, help_text='If true, this map is globally available.'),
        ),
        migrations.AlterField(
            model_name='editableroute',
            name='route_type',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('airsports', 'Air Sports Race'), ('airsportchallenge', 'AirSport Challenge'), ('poker', 'Poker run'), ('landing', 'Landing')], default='precision', max_length=200),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_scale',
            field=models.IntegerField(choices=[(25, '1:25,000'), (50, '1:50,000'), (100, '1:100,000'), (150, '1:150,000'), (200, '1:200,000'), (250, '1:250,000'), (300, '1:300,000'), (0, 'Fit page')], default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='calculator',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('airsports', 'Air Sports Race'), ('airsportchallenge', 'AirSport Challenge'), ('poker', 'Poker run'), ('landing', 'Landing')], default='precision', help_text='Supported calculator types', max_length=20),
        ),
        migrations.AlterField(
            model_name='useruploadedmap',
            name='map_file',
            field=models.FileField(help_text='File must be of type MBTILES. This can be generated for instance using MapTile Desktop', upload_to='user_uploaded_maps', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mbtiles']), display.models.validate_file_size]),
        ),
    ]
