# Generated by Django 4.1.7 on 2023-06-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0093_useruploadedmap_unprotected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmap',
            name='maximum_zoom_level',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='useruploadedmap',
            name='minimum_zoom_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useruploadedmap',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='map_thumbnails'),
        ),
    ]
