# Generated by Django 4.1.7 on 2023-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0094_useruploadedmap_maximum_zoom_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_source',
            field=models.CharField(blank=True, choices=[('norway', 'norway'), ('swiss', 'swiss-map-raster200_2021_14_krel_10_2056'), ('osm', 'OSM'), ('fc', 'Flight Contest'), ('mto', 'MapTiler Outdoor'), ('cyclosm', 'CycleOSM')], default='cyclosm', max_length=50),
        ),
    ]
