# Generated by Django 4.1.7 on 2023-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0095_alter_flightorderconfiguration_map_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedmap',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
