# Generated by Django 4.1.7 on 2023-06-15 19:14

import display.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0096_alter_useruploadedmap_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedmap',
            name='map_file',
            field=models.FileField(help_text='File must be of type MBTILES. This can be generated for instance using MapTile Desktop', max_length=500, upload_to='user_uploaded_maps', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mbtiles']), display.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='useruploadedmap',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='map_thumbnails'),
        ),
    ]
