# Generated by Django 4.1.7 on 2023-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0097_alter_useruploadedmap_map_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableroute',
            name='number_of_waypoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editableroute',
            name='route_length',
            field=models.FloatField(default=0, help_text='NM'),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_source',
            field=models.CharField(blank=True, choices=[], default='cyclosm', max_length=50),
        ),
    ]
