# Generated by Django 4.1.7 on 2023-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0099_useruploadedmap_default_zoom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmap',
            name='attribution',
            field=models.TextField(default='', help_text="A short attribution text for the map source material (source and time of retrieval), e.g. 'Contains data from kartverket.no, 07/2023"),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_zoom_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=12),
        ),
    ]
