# Generated by Django 4.1.7 on 2023-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0100_useruploadedmap_attribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedmap',
            name='attribution',
            field=models.TextField(default='', help_text="A short attribution text for the map source material (source and time of retrieval), e.g. 'Contains data from kartverket.no, 07/2023", max_length=100),
        ),
    ]
