# Generated by Django 4.1.7 on 2023-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0103_auto_20230718_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='longitude',
        ),
    ]
