# Generated by Django 4.1.7 on 2023-07-22 20:31

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0104_remove_contest_latitude_remove_contest_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='planning_time',
            field=models.IntegerField(default=30, help_text='The number of minutes each team has for planning the navigation task. This is only used for populating the planning time: in the starting table timeline.'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='location',
            field=location_field.models.plain.PlainLocationField(help_text='Text field with latitude, longitude (two comma-separated numbers). Select the location using the embedded map.', max_length=63),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_include_annotations',
            field=models.BooleanField(default=True, help_text='If this if set, the generated map will include minute marks and leg headings for the contestant so that no map preparation is necessary.'),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_include_meridians_and_parallels_lines',
            field=models.BooleanField(default=True, help_text='If true, navigation map is overlaid with meridians and parallels every 0.1 degrees. Disable if map source already has this'),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_plot_track_between_waypoints',
            field=models.BooleanField(default=True, help_text='For precision and Air Sport competition types this will draw a line between the waypoints of the track. Without this the precision map will only contain the waypoints, and the Air Sport maps will only contain the corridor without a centreline.'),
        ),
    ]
