# Generated by Django 4.1.7 on 2023-12-20 09:51

import display.fields.my_pickled_object_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0105_navigationtask_planning_time_alter_contest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editableroute',
            name='route',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False),
        ),
    ]
