# Generated by Django 4.1.7 on 2023-12-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0106_alter_editableroute_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='altitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
