# Generated by Django 5.0 on 2024-07-23 09:37

import display.fields.my_pickled_object_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0107_contestantreceivedposition_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='battery_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='device_id',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='position_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contestantreceivedposition',
            name='course',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='editableroute',
            name='route',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False, help_text='\n    List of route elements. Each route element is a dictionary with the required key "feature_type" which is used to \n    define the kind of route element that is being described. Legal values are: \n    [\'track\', \'to\', \'ldg\', \'prohibited_*\', \'info_*\', \'penalty_*\', \'gate_*\']. \n    Each element can be included multiple times except for \'track\' which can appear at most once.\n    '),
        ),
        migrations.AlterField(
            model_name='editableroute',
            name='route_type',
            field=models.CharField(choices=[('precision', 'Precision'), ('anr_corridor', 'ANR Corridor'), ('airsports', 'Air Sports Race'), ('airsportchallenge', 'AirSport Challenge'), ('poker', 'Poker run'), ('landing', 'Landing')], default='precision', help_text='Not used', max_length=200),
        ),
    ]
