# Generated by Django 5.0 on 2024-07-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0108_contestantreceivedposition_battery_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='track_version',
            field=models.IntegerField(default=0, help_text='Incremented whenever a new track is loaded from scratch either from traccar or from a gpx file.'),
        ),
        migrations.AddIndex(
            model_name='contestantreceivedposition',
            index=models.Index(fields=['contestant', 'time'], name='contestant_time_index'),
        ),
    ]
