# Generated by Django 5.0 on 2024-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0109_contestant_track_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='initial_score',
            field=models.FloatField(default=0, help_text='Initial score awarded to the contestant it start. This is typically 0, but if the penalties are negative, this can be set to some positive initial value.'),
        ),
    ]
