# Generated by Django 5.0 on 2024-08-04 14:57

import display.fields.my_pickled_object_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0110_scorecard_initial_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('_leg', display.fields.my_pickled_object_field.MyPickledObjectField(default=None, editable=False, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.route')),
            ],
        ),
    ]
