# Generated by Django 5.0 on 2024-08-04 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0111_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightorderconfiguration',
            name='photos_metres_across',
            field=models.FloatField(default=350, help_text='Approximately the number of metres on the ground that is covered by our observation photo'),
        ),
        migrations.AddField(
            model_name='flightorderconfiguration',
            name='photos_zoom_level',
            field=models.IntegerField(default=17, help_text='The tile zoom level used for generating photos from google satellite imagery', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
