# Generated by Django 5.0 on 2024-08-04 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0112_flightorderconfiguration_photos_metres_across_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightorderconfiguration",
            name="photos_metres_across",
        ),
        migrations.AddField(
            model_name="flightorderconfiguration",
            name="photos_meters_across",
            field=models.FloatField(
                default=350,
                help_text="Approximately the number of meters on the ground that is covered by our observation photo",
            ),
        ),
        migrations.AddField(
            model_name="flightorderconfiguration",
            name="turning_point_photos_meters_across",
            field=models.FloatField(
                default=1400,
                help_text="Approximately the number of meters on the ground that is covered by the turning point photo",
            ),
        ),
        migrations.AddField(
            model_name="flightorderconfiguration",
            name="turning_points_photo_zoom_level",
            field=models.IntegerField(
                default=15,
                help_text="The tile zoom level used for generating turning point photos from google satellite imagery",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AddField(
            model_name="flightorderconfiguration",
            name="unknown_leg_photos_meters_across",
            field=models.FloatField(
                default=1400,
                help_text="Approximately the number of meters on the ground that is covered by the unknown leg photo",
            ),
        ),
        migrations.AddField(
            model_name="flightorderconfiguration",
            name="unknown_leg_photos_zoom_level",
            field=models.IntegerField(
                default=15,
                help_text="The tile zoom level used for generating unknown leg photos from google satellite imagery",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)],
            ),
        ),
    ]
