# Generated by Django 5.0 on 2024-08-21 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0115_alter_flightorderconfiguration_unknown_leg_photos_zoom_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlymasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contestant',
            name='air_speed',
            field=models.FloatField(default=70, help_text='The planned airspeed for the contestant', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='tracking_service',
            field=models.CharField(choices=[('traccar', 'Airsports'), ('flymaster', 'Flymaster')], default='traccar', help_text="Supported tracking services: <enum 'TrackingService'>", max_length=30),
        ),
        migrations.AlterField(
            model_name='contestteam',
            name='tracking_service',
            field=models.CharField(choices=[('traccar', 'Airsports'), ('flymaster', 'Flymaster')], default='traccar', help_text="Supported tracking services: <enum 'TrackingService'>", max_length=30),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='include_turning_point_images',
            field=models.BooleanField(default=False, help_text='Includes one or more pages with aerial photos of each turning point (turns in a anr corridor is not considered a turning point).'),
        ),
    ]
