# Generated by Django 5.0 on 2024-08-11 12:03

import datetime
import display.fields.my_pickled_object_field
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def convert_predefined_to_relative(apps, schema_editor):
    for contestant in apps.get_model("display", "Contestant").objects.all():
        if contestant.predefined_gate_times is not None:
            contestant._relative_gate_times = {}
            starting_point_time = contestant.takeoff_time + datetime.timedelta(
                minutes=contestant.navigation_task.minutes_to_starting_point
            )
            for name, time in contestant.predefined_gate_times.items():
                contestant._relative_gate_times[name] = time - starting_point_time


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0115_alter_flightorderconfiguration_unknown_leg_photos_zoom_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestant",
            name="_relative_gate_times",
            field=display.fields.my_pickled_object_field.MyPickledObjectField(
                blank=True,
                default=None,
                editable=False,
                help_text="Dictionary of gates and their passing time deltas relative to starting point",
                null=True,
            ),
        ),
        migrations.RunPython(convert_predefined_to_relative),
        migrations.RemoveField(
            model_name="contestant",
            name="predefined_gate_times",
        ),
        migrations.AddField(
            model_name="contestant",
            name="minutes_from_last_gate_to_landing",
            field=models.FloatField(
                default=30,
                help_text="The number of minutes from the the final gate until the contestant should have landed. This will be the time of the landing gate if it exists",
            ),
        ),
        migrations.AddField(
            model_name="contestant",
            name="route",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="display.route"),
        ),
    ]
