# Generated by Django 5.0 on 2025-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0118_alter_scorecard_prohibited_zone_maximum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='prohibited_zone_maximum',
            field=models.FloatField(default=0, help_text='The maximum score that can be given for entering prohibited zones. Zero means the maximum is ignored'),
        ),
    ]
