# Generated by Django 5.0 on 2025-12-28 21:26

from django.db import migrations

from display.convert_route import convert_legacy_json

def migrate_editable_routes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    EditableRoute = apps.get_model("display", "EditableRoute")
    for editable_route in EditableRoute.objects.using(db_alias).all():
        editable_route.route=convert_legacy_json(editable_route.route)
        editable_route.save()

class Migration(migrations.Migration):

    dependencies = [
        ('display', '0119_alter_scorecard_prohibited_zone_maximum'),
    ]

    operations = [
        migrations.RunPython(migrate_editable_routes),
    ]
