# Generated by Django 5.0 on 2025-12-30 09:42

import display.fields.my_pickled_object_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0120_auto_20251228_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='corridor_polygon',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False),
        ),
    ]
