# Generated by Django 5.0 on 2025-12-30 15:26

import display.fields.my_pickled_object_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0121_route_corridor_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableroute',
            name='settings',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=dict, editable=False, help_text='Settings for the route editor'),
        ),
    ]
