# Generated by Django 6.0.1 on 2026-01-15 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0122_editableroute_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_dpi',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
