# Generated by Django 6.0.1 on 2026-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0123_alter_flightorderconfiguration_map_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='schedule_locked',
            field=models.BooleanField(default=False, help_text="If true, the contestant's timing should not be modified by the scheduling algorithm."),
        ),
    ]
