# Generated by Django 6.0.1 on 2026-01-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0124_contestant_schedule_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationtask',
            name='schedule_start_time',
            field=models.DateTimeField(blank=True, help_text='The first takeoff time when the contestant scheduler was last run', null=True),
        ),
    ]
