# Generated by Django 6.0.1 on 2026-01-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0125_navigationtask_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationtask',
            name='planning_time',
            field=models.IntegerField(default=45, help_text='The number of minutes each team has for planning the navigation task. This is only used for populating the planning time: in the starting table timeline.'),
        ),
    ]
