# Generated by Django 6.0.1 on 2026-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0126_alter_navigationtask_planning_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationtask',
            name='score_sorting_direction',
        ),
        migrations.AddField(
            model_name='contestant',
            name='declared_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object storing pilot declarations (leg speeds, waypoint order, times)'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='circle_altitude_penalty',
            field=models.FloatField(default=0.2, help_text='Percentage penalty (0.0-1.0) for altitude violation in circle'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='circle_altitude_tolerance',
            field=models.FloatField(default=61, help_text='Altitude tolerance for circle task (meters)'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='circle_min_radius_ratio',
            field=models.FloatField(default=0.5, help_text='Ratio of min/max radius below which score is zero'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='circle_performance_factor',
            field=models.FloatField(default=500, help_text='Factor used in circle scoring formula'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='free_point_missed_penalty',
            field=models.FloatField(default=0, help_text='Points deducted if a declared free point is missed'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='free_waypoint_score',
            field=models.FloatField(default=100, help_text='Points awarded for visiting a free waypoint (e.g. Turnpoint Hunt)'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='score_sorting_direction',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', help_text='The direction to sort the scores in the scoreboard', max_length=4),
        ),
    ]
