# Generated by Django 6.0.1 on 2026-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0126_alter_navigationtask_planning_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationtask',
            name='score_sorting_direction',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='score_sorting_direction',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', help_text='The direction to sort the scores in the scoreboard', max_length=4),
        ),
    ]
