# Generated by Django 6.0.1 on 2026-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0127_remove_navigationtask_score_sorting_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='corridor_maximum_penalty_is_per_leg',
            field=models.BooleanField(default=False, help_text='If true, the maximum corridor penalty is reset for each leg'),
        ),
    ]
