# Generated by Django 6.0.1 on 2026-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0127_remove_navigationtask_score_sorting_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='re_crossing_penalty',
            field=models.FloatField(default=50, help_text='Penalty for crossing a gate that has already been passed (CIMA 2.A1/2.A2)'),
        ),
    ]
