# Generated by Django 6.0.1 on 2026-02-01 13:58

import display.fields.my_pickled_object_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0128_scorecard_re_crossing_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='standalone_waypoints',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False),
        ),
    ]
