# Generated by Django 6.0.1 on 2026-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0128_scorecard_corridor_maximum_penalty_is_per_leg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='corridor_maximum_penalty_is_per_leg',
            field=models.BooleanField(default=True, help_text='If true, the maximum corridor penalty is reset for each leg'),
        ),
    ]
