# Generated by Django 6.0.1 on 2026-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0129_alter_scorecard_corridor_maximum_penalty_is_per_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='projected_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestantreceivedposition',
            name='projected_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
