# Generated by Django 6.0.1 on 2026-02-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0129_route_standalone_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='custom_route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestant_override', to='display.route'),
        ),
    ]
