# Generated by Django 6.0.1 on 2026-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0131_useruploadedmap_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscribers',
            },
        ),
        migrations.AlterField(
            model_name='gatescore',
            name='gate_type',
            field=models.CharField(choices=[('tp', 'Turning Point'), ('sp', 'Starting Point'), ('fp', 'Finish Point'), ('secret', 'Secret Point'), ('anrtp', 'ANR Turning Point'), ('to', 'Takeoff Gate'), ('ldg', 'Landing Gate'), ('isp', 'Intermediary Starting Point'), ('ifp', 'Intermediary Finish Point'), ('dummy', 'Dummy'), ('ul', 'Unknown leg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='finish_time',
            field=models.DateTimeField(help_text='The finish time of the navigation task. Determines the time interval where the navigation task is available for self registration if selected.'),
        ),
        migrations.AlterField(
            model_name='navigationtask',
            name='start_time',
            field=models.DateTimeField(help_text='The start time of the navigation task. Determines the time interval where the navigation task is available for self registration if selected.'),
        ),
        migrations.AlterField(
            model_name='trackannotation',
            name='gate_type',
            field=models.CharField(blank=True, choices=[('tp', 'Turning Point'), ('sp', 'Starting Point'), ('fp', 'Finish Point'), ('secret', 'Secret Point'), ('anrtp', 'ANR Turning Point'), ('to', 'Takeoff Gate'), ('ldg', 'Landing Gate'), ('isp', 'Intermediary Starting Point'), ('ifp', 'Intermediary Finish Point'), ('dummy', 'Dummy'), ('ul', 'Unknown leg')], default='tp', max_length=30),
        ),
    ]
