# Generated by Django 6.0.1 on 2026-04-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0132_newslettersubscriber_alter_gatescore_gate_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.CreateModel(
            name='HighlightedContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When the highlighting period starts')),
                ('finish_time', models.DateTimeField(help_text='When the highlighting period ends')),
                ('blurb', models.TextField(help_text='A nice description of why this contest is highlighted')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.contest')),
            ],
        ),
    ]
