# Generated by Django 6.0.1 on 2026-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0133_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
