# Generated by Django 6.0.1 on 2026-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0134_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='score_version',
            field=models.IntegerField(default=0, help_text='Incremented whenever score-related data (e.g. poker cards, administrative penalty removals) is modified after calculation.'),
        ),
    ]
