# Generated by Django 6.0.1 on 2026-07-09 10:51

import display.fields.my_pickled_object_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0135_contestant_score_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editableroute',
            name='route',
            field=display.fields.my_pickled_object_field.MyPickledObjectField(default=list, editable=False, help_text='\n    List of route elements. Each route element is a dictionary with the required key "feature_type" which is used to \n    define the kind of route element that is being described. Legal values are: \n    [\'track\', \'to\', \'ldg\', \'prohibited_*\', \'info_*\', \'penalty_*\']. \n    Each element can be included multiple times except for \'track\' which can appear at most once.\n    '),
        ),
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_source',
            field=models.CharField(blank=True, default='cyclosm', max_length=50),
        ),
    ]
