# Generated by Django 6.0.1 on 2026-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0136_alter_editableroute_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightorderconfiguration',
            name='map_source',
            field=models.CharField(blank=True, choices=[], default='cyclosm', max_length=50),
        ),
    ]
