# Generated by Django 6.0.1 on 2026-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0137_alter_flightorderconfiguration_map_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmap',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruploadedmap',
            name='published_relative_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='useruploadedmap',
            name='published_service_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
