# Generated by Django 6.0.1 on 2026-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0138_useruploadedmap_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmap',
            name='maximum_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruploadedmap',
            name='maximum_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruploadedmap',
            name='minimum_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruploadedmap',
            name='minimum_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
