# Generated by Hermes Agent on 2026-07-14

from django.db import migrations


def backfill_shared_storage(apps, schema_editor):
    UserUploadedMap = apps.get_model("display", "UserUploadedMap")

    for uploaded_map in UserUploadedMap.objects.exclude(map_file=""):
        service_key = uploaded_map.published_service_key or f"user-uploaded-map-{uploaded_map.pk}"
        relative_path = uploaded_map.published_relative_path or f"user_uploaded_maps/{service_key}.mbtiles"

        fields_to_update = []
        if uploaded_map.published_service_key != service_key:
            uploaded_map.published_service_key = service_key
            fields_to_update.append("published_service_key")
        if uploaded_map.published_relative_path != relative_path:
            uploaded_map.published_relative_path = relative_path
            fields_to_update.append("published_relative_path")
        if fields_to_update:
            uploaded_map.save(update_fields=fields_to_update)


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0140_unify_flightorderconfiguration_map_source"),
    ]

    operations = [
        migrations.RunPython(backfill_shared_storage, migrations.RunPython.noop),
    ]
