# Generated by Django 6.0.1 on 2026-07-19 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0143_access_control_and_contest_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('contestant_limit', models.IntegerField()),
                ('task_limit', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('single_event', 'Single event'), ('annual_club_pass', 'Annual club pass'), ('manual_override', 'Manual override'), ('token', 'Token')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserTokenGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.IntegerField()),
                ('quantity_consumed', models.IntegerField(default=0)),
                ('purchase_reference', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_token_grants', to=settings.AUTH_USER_MODEL)),
                ('token_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='display.tokentype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_token_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContestTokenAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contest_tokens', to=settings.AUTH_USER_MODEL)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.contest')),
                ('token_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='display.tokentype')),
                ('token_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='display.usertokengrant')),
            ],
            options={
                'ordering': ('-assigned_at',),
            },
        ),
    ]
