# Generated by Hermes on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0145_contestusageledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestusageledger",
            name="team",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to="display.team"),
        ),
        migrations.RemoveConstraint(
            model_name="contestusageledger",
            name="unique_contestant_started_usage",
        ),
        migrations.RemoveConstraint(
            model_name="contestusageledger",
            name="unique_task_started_usage",
        ),
        migrations.AddConstraint(
            model_name="contestusageledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "contest_team_started")),
                fields=("contest", "team", "kind"),
                name="unique_contest_team_started_usage",
            ),
        ),
        migrations.AddConstraint(
            model_name="contestusageledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "task_team_started")),
                fields=("contest", "navigation_task", "team", "kind"),
                name="unique_task_team_started_usage",
            ),
        ),
    ]
