# Generated by Hermes on 2026-07-21

from django.db import migrations, models


def backfill_pilot_from_team(apps, schema_editor):
    ContestUsageLedger = apps.get_model("display", "ContestUsageLedger")
    for row in ContestUsageLedger.objects.select_related("team__crew").all().iterator():
        if row.team_id and row.team and row.team.crew_id:
            row.pilot_id = row.team.crew.member1_id
            if row.kind == "contest_team_started":
                row.kind = "contest_pilot_started"
            elif row.kind == "task_team_started":
                row.kind = "task_pilot_started"
            row.save(update_fields=["pilot", "kind"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0146_team_based_usage_ledgers"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestusageledger",
            name="pilot",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to="display.person"),
        ),
        migrations.RunPython(backfill_pilot_from_team, noop_reverse),
        migrations.RemoveConstraint(
            model_name="contestusageledger",
            name="unique_contest_team_started_usage",
        ),
        migrations.RemoveConstraint(
            model_name="contestusageledger",
            name="unique_task_team_started_usage",
        ),
        migrations.AddConstraint(
            model_name="contestusageledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "contest_pilot_started")),
                fields=("contest", "pilot", "kind"),
                name="unique_contest_pilot_started_usage",
            ),
        ),
        migrations.AddConstraint(
            model_name="contestusageledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "task_pilot_started")),
                fields=("contest", "navigation_task", "pilot", "kind"),
                name="unique_task_pilot_started_usage",
            ),
        ),
    ]
