# Generated by Hermes on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0147_pilot_identity_usage_ledgers"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokentype",
            name="validity_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contesttokenassignment",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contesttokenassignment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
