# Generated by Hermes on 2026-07-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0148_token_assignment_validity_windows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokentype",
            name="task_limit",
        ),
        migrations.RemoveField(
            model_name="accessgrant",
            name="task_limit",
        ),
    ]
