# Generated by Hermes on 2026-07-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0149_remove_task_limit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmanagermembership",
            name="created_by",
            field=models.ForeignKey(blank=True, help_text="Backend user who created this club manager membership.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_club_manager_memberships", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="clubmanagermembership",
            name="updated_by",
            field=models.ForeignKey(blank=True, help_text="Backend user who last updated this club manager membership.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_club_manager_memberships", to=settings.AUTH_USER_MODEL),
        ),
    ]
