# Generated by Django 6.0.1 on 2026-07-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0152_compiled_navigation_task_and_contestant_task_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativePenalty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quarantine", "Quarantine"),
                            ("fuel", "Fuel check"),
                            ("instructions", "Task instructions"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "contestant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="display.contestant"),
                ),
                (
                    "score_log_entry",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="display.scorelogentry"),
                ),
            ],
        ),
    ]
