# Generated by Django 6.0.1 on 2026-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0153_administrativepenalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativepenalty",
            name="category",
            field=models.CharField(
                choices=[
                    ("quarantine", "Quarantine"),
                    ("fuel", "Fuel check"),
                    ("instructions", "Task instructions"),
                    ("observation", "Observation evidence"),
                    ("map", "Map placement"),
                ],
                max_length=40,
            ),
        ),
    ]
