from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds indexes to the three exact-match columns the live position-ingest
    path (Contestant.get_contestant_for_device_at_time, via
    _try_to_get_tracker_tracking/_try_to_get_pilot_tracking/_try_to_get_copilot_tracking)
    filters on for every incoming Traccar position that misses the
    ~60s-TTL in-process contestant cache in position_processor_process.py.
    None of these had an index before. Hand-written rather than generated by
    makemigrations, which also picked up a large backlog of unrelated
    pre-existing model drift (help_text/verbose_name-only AlterField diffs
    with no DB effect) - this migration touches only the three fields
    actually changed.
    """

    dependencies = [
        ("display", "0165_alter_flightorderconfiguration_map_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestant",
            name="tracker_device_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of physical tracking device that will be brought into the plane. If using the Air Sports Live Tracking app this should be left blank.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="app_tracking_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="An automatically generated tracking ID which is distributed to the tracking app",
                max_length=28,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="simulator_tracking_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="An automatically generated tracking ID which is distributed to the simulator integration. Persons or contestants identified by this field should not be displayed on the global map.",
                max_length=28,
            ),
        ),
    ]
