# Generated by Django 6.0.1 on 2026-08-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0166_add_tracking_id_indexes'),
        ('display', '0166_route_task_type_compatibility'),
    ]

    operations = [
    ]
