# Generated by Django 6.0.1 on 2026-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0175_delete_gatescore'),
        ('display', '0175_fix_corridor_polygon_sp_fp_width'),
    ]

    operations = [
    ]
