# Generated by Django 6.1.1 on 2026-09-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0179_contestcreator_group_add_editableroute_permission'),
        ('display', '0179_fix_tracking_pilot_and_copilot_constant'),
    ]

    operations = [
    ]
