# Generated by Django 6.1.1 on 2026-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0180_flight_order_configuration_map_scale_help_text'),
        ('display', '0180_merge_20260913_1629'),
    ]

    operations = [
    ]
