# Generated by Django 5.0 on 2025-12-30 15:40
from display.models import NavigationTask
from display.utilities.navigation_task_type_definitions import PRECISION, POKER, ANR_CORRIDOR, AIRSPORTS, AIRSPORT_CHALLENGE


def migrate():
    for navigation_task in NavigationTask.objects.all():
        if navigation_task.editable_route is None:
            continue
        route = None
        try:
            if navigation_task.scorecard.calculator in (PRECISION, POKER):
                route = navigation_task.editable_route.create_precision_route(navigation_task.route.use_procedure_turns, navigation_task.scorecard)
            elif navigation_task.scorecard.calculator == ANR_CORRIDOR:
                route = navigation_task.editable_route.create_anr_route(
                    navigation_task.route.rounded_corners, navigation_task.route.corridor_width, navigation_task.scorecard
                )
            elif navigation_task.scorecard.calculator in (AIRSPORTS, AIRSPORT_CHALLENGE):
                route = navigation_task.editable_route.create_airsports_route(navigation_task.route.rounded_corners, navigation_task.scorecard)
            if route:
                old_route = navigation_task.route
                navigation_task.route = route
                navigation_task.save()
                old_route.delete()
        except Exception as e:
            print(f"Failed to migrate route for NavigationTask id={navigation_task.id}: {e}")



if __name__ == "__main__":
    migrate()
    