apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-wordpress-cm
data:
  wordpress-htaccess.conf: |
    php_value upload_max_filesize 512M
    php_value post_max_size 512M
    php_value max_execution_time 300
    php_value max_input_time 300